-- STEP 2: Auth 사용자 프로필, RBAC, 감사 로그
--
-- 원칙
-- 1. auth.users는 Supabase Auth가 관리하고, 업무용 사용자 정보는 core.app_user에 둡니다.
-- 2. 권한은 클라이언트가 아닌 core.is_admin()과 RLS가 판정합니다.
-- 3. 기존 raw/analytics 계산 SQL은 변경하지 않습니다.

create schema if not exists core;

create table if not exists core.app_user (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  name text not null default '',
  department text,
  role text not null default 'USER' check (role in ('ADMIN', 'USER')),
  active boolean not null default true,
  last_login_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists app_user_email_uidx on core.app_user(lower(email));

create table if not exists core.audit_log (
  id bigint generated by default as identity primary key,
  actor uuid references auth.users(id) on delete set null,
  action text not null,
  target_type text not null,
  target_id text not null,
  before jsonb,
  after jsonb,
  "at" timestamptz not null default now()
);

create index if not exists audit_log_target_idx on core.audit_log(target_type, target_id);
create index if not exists audit_log_at_idx on core.audit_log("at" desc);

create or replace function core.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists app_user_set_updated_at on core.app_user;
create trigger app_user_set_updated_at
before update on core.app_user
for each row execute function core.set_updated_at();

-- RLS와 trigger에서 함께 사용하는 DB 권한 판정 함수입니다.
create or replace function core.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from core.app_user as u
    where u.user_id = (select auth.uid())
      and u.role = 'ADMIN'
      and u.active = true
  );
$$;

-- 로그인 직후 last_login_at만 갱신합니다. 직접 UPDATE 권한은 주지 않습니다.
create or replace function core.touch_last_login()
returns void
language sql
volatile
security definer
set search_path = ''
as $$
  update core.app_user
     set last_login_at = now(), updated_at = now()
   where user_id = (select auth.uid())
     and active = true;
$$;

-- Auth 사용자 생성 시 업무용 프로필을 자동으로 만듭니다.
create or replace function core.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  display_name text;
begin
  display_name := coalesce(
    new.raw_user_meta_data ->> 'name',
    new.raw_user_meta_data ->> 'full_name',
    split_part(coalesce(new.email, ''), '@', 1),
    ''
  );

  insert into core.app_user (user_id, email, name)
  values (new.id, coalesce(new.email, ''), display_name)
  on conflict (user_id) do update
    set email = excluded.email,
        updated_at = now();

  return new;
end;
$$;

drop trigger if exists on_auth_user_created_app_user on auth.users;
create trigger on_auth_user_created_app_user
after insert on auth.users
for each row execute function core.handle_new_user();

-- migration 적용 시점에 이미 존재하는 Auth 사용자도 보정합니다.
insert into core.app_user (user_id, email, name)
select
  u.id,
  coalesce(u.email, ''),
  coalesce(
    u.raw_user_meta_data ->> 'name',
    u.raw_user_meta_data ->> 'full_name',
    split_part(coalesce(u.email, ''), '@', 1),
    ''
  )
from auth.users as u
on conflict (user_id) do update
  set email = excluded.email,
      updated_at = now();

-- role/active 변경은 DB에서 자기 자신을 잠그지 못하도록 막습니다.
create or replace function core.prevent_self_lockout()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if (select auth.uid()) is not null
     and old.user_id = (select auth.uid())
     and (new.role is distinct from old.role or new.active is distinct from old.active) then
    raise exception 'SELF_LOCKOUT_FORBIDDEN'
      using errcode = '42501';
  end if;
  return new;
end;
$$;

drop trigger if exists app_user_prevent_self_lockout on core.app_user;
create trigger app_user_prevent_self_lockout
before update on core.app_user
for each row execute function core.prevent_self_lockout();

-- 관리자 변경은 서버 코드가 우회하지 못하도록 DB trigger에서 반드시 기록합니다.
create or replace function core.audit_app_user_changes()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  change_action text;
begin
  if new.role is not distinct from old.role
     and new.active is not distinct from old.active then
    return new;
  end if;

  change_action := case
    when new.role is distinct from old.role and new.active is distinct from old.active
      then 'APP_USER_ROLE_AND_STATUS_CHANGED'
    when new.role is distinct from old.role
      then 'APP_USER_ROLE_CHANGED'
    else 'APP_USER_STATUS_CHANGED'
  end;

  insert into core.audit_log (actor, action, target_type, target_id, before, after)
  values (
    (select auth.uid()),
    change_action,
    'app_user',
    new.user_id::text,
    jsonb_build_object('role', old.role, 'active', old.active),
    jsonb_build_object('role', new.role, 'active', new.active)
  );

  return new;
end;
$$;

drop trigger if exists app_user_audit_changes on core.app_user;
create trigger app_user_audit_changes
after update on core.app_user
for each row execute function core.audit_app_user_changes();

-- API 접근면을 닫고, 로그인한 사용자에게 필요한 읽기와 관리자 mutation만 허용합니다.
revoke all on schema core from anon;
revoke all on schema analytics from anon;
grant usage on schema core to authenticated;
grant usage on schema analytics to authenticated;

revoke all on all tables in schema core from anon;
revoke all on all tables in schema analytics from anon;
revoke all on all tables in schema public from anon;

grant select on all tables in schema analytics to authenticated;
grant select on all tables in schema core to authenticated;

grant select on core.app_user to authenticated;
grant update on core.app_user to authenticated;
grant select on core.audit_log to authenticated;

grant select on core.leadtime_plan, core.usage_profile, core.supplier_alias to authenticated;
grant insert, update, delete on core.leadtime_plan, core.usage_profile, core.supplier_alias to authenticated;

-- 새로 만들어질 core/analytics 객체도 anon에게 열리지 않도록 기본 권한을 고정합니다.
alter default privileges in schema core revoke all on tables from anon;
alter default privileges in schema analytics revoke all on tables from anon;
alter default privileges in schema core grant select on tables to authenticated;
alter default privileges in schema analytics grant select on tables to authenticated;

-- app_user: 본인 프로필 또는 관리자는 조회, 변경은 관리자만 가능
alter table core.app_user enable row level security;
drop policy if exists app_user_select_self_or_admin on core.app_user;
create policy app_user_select_self_or_admin
on core.app_user
for select
to authenticated
using (
  user_id = (select auth.uid())
  or (select core.is_admin())
);

drop policy if exists app_user_update_admin_only on core.app_user;
create policy app_user_update_admin_only
on core.app_user
for update
to authenticated
using ((select core.is_admin()))
with check ((select core.is_admin()));

-- audit_log: 기록은 trigger만 만들고, 조회는 관리자만 허용
alter table core.audit_log enable row level security;
drop policy if exists audit_log_select_admin_only on core.audit_log;
create policy audit_log_select_admin_only
on core.audit_log
for select
to authenticated
using ((select core.is_admin()));

-- 기준값은 로그인한 사용자가 조회할 수 있지만, mutation은 관리자만 가능합니다.
alter table core.leadtime_plan enable row level security;
alter table core.usage_profile enable row level security;
alter table core.supplier_alias enable row level security;

drop policy if exists leadtime_plan_select_authenticated on core.leadtime_plan;
create policy leadtime_plan_select_authenticated
on core.leadtime_plan for select to authenticated using ((select auth.uid()) is not null);
drop policy if exists leadtime_plan_admin_mutation on core.leadtime_plan;
create policy leadtime_plan_admin_mutation
on core.leadtime_plan for all to authenticated
using ((select core.is_admin())) with check ((select core.is_admin()));

drop policy if exists usage_profile_select_authenticated on core.usage_profile;
create policy usage_profile_select_authenticated
on core.usage_profile for select to authenticated using ((select auth.uid()) is not null);
drop policy if exists usage_profile_admin_mutation on core.usage_profile;
create policy usage_profile_admin_mutation
on core.usage_profile for all to authenticated
using ((select core.is_admin())) with check ((select core.is_admin()));

drop policy if exists supplier_alias_select_authenticated on core.supplier_alias;
create policy supplier_alias_select_authenticated
on core.supplier_alias for select to authenticated using ((select auth.uid()) is not null);
drop policy if exists supplier_alias_admin_mutation on core.supplier_alias;
create policy supplier_alias_admin_mutation
on core.supplier_alias for all to authenticated
using ((select core.is_admin())) with check ((select core.is_admin()));

-- public training/raw 영역은 RLS가 켜져 있어도 anon grant가 남으면 접근면이 열릴 수 있어
-- anon 권한을 명시적으로 회수합니다. 기존 계산 데이터는 변경하지 않습니다.
revoke insert, update, delete, truncate on all tables in schema public from authenticated;

-- 기존 분석 RPC도 anon에게는 노출하지 않습니다.
revoke all on function public.get_leadtime_gap() from public;
grant execute on function public.get_leadtime_gap() to authenticated;

-- SECURITY DEFINER 함수는 공개 실행 권한을 제거하고 필요한 역할에만 부여합니다.
revoke all on function core.is_admin() from public;
grant execute on function core.is_admin() to authenticated;
revoke all on function core.touch_last_login() from public;
grant execute on function core.touch_last_login() to authenticated;
revoke all on function core.handle_new_user() from public;
revoke all on function core.prevent_self_lockout() from public;
revoke all on function core.audit_app_user_changes() from public;
revoke all on function core.set_updated_at() from public;
