-- STEP 7: 저장된 Forecast Result와 분리된 검증 Actual을 이용한
-- 백테스트, 모델 성능, Champion 이력 구조입니다.
--
-- 원칙
-- 1. Forecast를 다시 계산하지 않습니다. core.forecast_result만 읽습니다.
-- 2. 검증 Actual은 core.v_test_actual만 사용합니다.
-- 3. 채점은 이 SQL 함수에서 수행하며 화면 컴포넌트에는 계산식을 두지 않습니다.
-- 4. Champion은 삭제/갱신하지 않고 선택 이력을 누적합니다.

create table if not exists core.model_config (
  model_id text not null,
  model_version text not null,
  model_name text not null,
  description text,
  enabled boolean not null default true,
  is_baseline boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (model_id, model_version)
);

create table if not exists core.forecast_result (
  forecast_result_id bigint generated by default as identity primary key,
  forecast_run_id uuid not null references core.forecast_run(forecast_run_id) on delete cascade,
  model_id text not null,
  model_version text not null,
  item_id text not null,
  forecast_date date not null,
  forecast_value numeric,
  p50 numeric,
  p80 numeric,
  p90 numeric,
  prediction_lower numeric,
  prediction_upper numeric,
  result_reason_code text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (forecast_run_id, model_id, model_version, item_id, forecast_date),
  constraint forecast_result_model_fk foreign key (model_id, model_version)
    references core.model_config(model_id, model_version)
);

create table if not exists core.backtest_run (
  backtest_run_id uuid primary key default gen_random_uuid(),
  forecast_run_id uuid not null references core.forecast_run(forecast_run_id),
  test_start date not null,
  test_end date not null,
  metric text not null,
  status text not null default 'RUNNING',
  triggered_by uuid references auth.users(id) on delete set null,
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  error_code text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint backtest_run_metric_ck check (metric in ('WAPE', 'MAPE', 'RMSE', 'MAE')),
  constraint backtest_run_status_ck check (status in ('RUNNING', 'COMPLETED', 'FAILED')),
  constraint backtest_run_range_ck check (test_start <= test_end)
);

create table if not exists core.model_performance (
  performance_id bigint generated by default as identity primary key,
  backtest_run_id uuid not null references core.backtest_run(backtest_run_id) on delete cascade,
  forecast_run_id uuid not null references core.forecast_run(forecast_run_id),
  model_id text not null,
  model_version text not null,
  item_id text not null,
  test_start date not null,
  test_end date not null,
  metric text not null,
  periods_total integer not null default 0,
  actual_periods integer not null default 0,
  forecast_periods integer not null default 0,
  comparable_periods integer not null default 0,
  actual_abs_sum numeric,
  wape numeric,
  mape numeric,
  bias numeric,
  rmse numeric,
  mae numeric,
  metric_value numeric,
  baseline_improvement numeric,
  rank integer,
  status text not null,
  reason_code text,
  calculated_at timestamptz not null default now(),
  constraint model_performance_metric_ck check (metric in ('WAPE', 'MAPE', 'RMSE', 'MAE')),
  constraint model_performance_status_ck check (status in ('VALID', 'CALCULATION_UNAVAILABLE')),
  constraint model_performance_model_fk foreign key (model_id, model_version)
    references core.model_config(model_id, model_version),
  unique (backtest_run_id, model_id, model_version, item_id)
);

create table if not exists core.champion_model (
  champion_model_id bigint generated by default as identity primary key,
  item_id text not null,
  model_id text not null,
  model_version text not null,
  metric text not null,
  metric_value numeric not null,
  baseline_improvement numeric,
  backtest_run_id uuid not null references core.backtest_run(backtest_run_id),
  forecast_run_id uuid not null references core.forecast_run(forecast_run_id),
  candidate_performance jsonb not null default '[]'::jsonb,
  selection_method text not null,
  selection_reason text not null,
  selected_by uuid references auth.users(id) on delete set null,
  selected_at timestamptz not null default now(),
  constraint champion_model_metric_ck check (metric in ('WAPE', 'MAPE', 'RMSE', 'MAE')),
  constraint champion_model_method_ck check (selection_method in ('AUTO', 'MANUAL')),
  constraint champion_model_model_fk foreign key (model_id, model_version)
    references core.model_config(model_id, model_version)
);

create table if not exists core.champion_selection_log (
  selection_log_id bigint generated by default as identity primary key,
  backtest_run_id uuid not null references core.backtest_run(backtest_run_id) on delete cascade,
  item_id text not null,
  metric text not null,
  selection_method text not null,
  selected_model_id text,
  selected_model_version text,
  candidate_count integer not null default 0,
  valid_candidate_count integer not null default 0,
  selection_reason text not null,
  reason_code text,
  selected_by uuid references auth.users(id) on delete set null,
  selected_at timestamptz not null default now(),
  constraint champion_selection_log_metric_ck check (metric in ('WAPE', 'MAPE', 'RMSE', 'MAE')),
  constraint champion_selection_log_method_ck check (selection_method in ('AUTO', 'MANUAL'))
);

alter table core.forecast_setting
  add column if not exists champion_metric text not null default 'WAPE',
  add column if not exists baseline_model_id text,
  add column if not exists baseline_model_version text;

alter table core.forecast_run
  add column if not exists forecast_setting_key text not null default 'DEFAULT',
  add column if not exists triggered_by uuid references auth.users(id) on delete set null,
  add column if not exists train_start date,
  add column if not exists train_end date;

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'forecast_setting_champion_metric_ck') then
    alter table core.forecast_setting
      add constraint forecast_setting_champion_metric_ck
      check (champion_metric in ('WAPE', 'MAPE', 'RMSE', 'MAE'));
  end if;
  if not exists (select 1 from pg_constraint where conname = 'forecast_setting_baseline_pair_ck') then
    alter table core.forecast_setting
      add constraint forecast_setting_baseline_pair_ck
      check ((baseline_model_id is null) = (baseline_model_version is null));
  end if;
  if not exists (select 1 from pg_constraint where conname = 'forecast_setting_baseline_fk') then
    alter table core.forecast_setting
      add constraint forecast_setting_baseline_fk
      foreign key (baseline_model_id, baseline_model_version)
      references core.model_config(model_id, model_version);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'forecast_run_setting_fk') then
    alter table core.forecast_run
      add constraint forecast_run_setting_fk
      foreign key (forecast_setting_key) references core.forecast_setting(setting_key);
  end if;
end;
$$;

insert into core.model_config (model_id, model_version, model_name, description, enabled, is_baseline)
values
  ('NAIVE', '1.0', 'Naive', '가장 최근 관측값을 기준으로 하는 기준 모델', true, true),
  ('MOVING_AVERAGE', '1.0', 'Moving Average', '최근 관측값 이동평균 모델', true, false),
  ('SEASONAL_NAIVE', '1.0', 'Seasonal Naive', '계절 주기 기준 모델', true, false)
on conflict (model_id, model_version) do nothing;

update core.forecast_setting
   set champion_metric = coalesce(champion_metric, 'WAPE'),
       baseline_model_id = coalesce(baseline_model_id, 'NAIVE'),
       baseline_model_version = coalesce(baseline_model_version, '1.0'),
       updated_at = now()
 where setting_key = 'DEFAULT';

update core.forecast_run as r
   set train_start = coalesce(r.train_start, s.train_start),
       train_end = coalesce(r.train_end, s.train_end)
  from core.forecast_setting as s
 where r.forecast_setting_key = s.setting_key;

create index if not exists forecast_result_run_item_date_idx
  on core.forecast_result(forecast_run_id, item_id, forecast_date);
create index if not exists forecast_result_model_idx
  on core.forecast_result(model_id, model_version);
create index if not exists backtest_run_forecast_idx
  on core.backtest_run(forecast_run_id, started_at desc);
create index if not exists backtest_run_triggered_by_idx
  on core.backtest_run(triggered_by);
create index if not exists model_performance_lookup_idx
  on core.model_performance(backtest_run_id, item_id, metric_value);
create index if not exists model_performance_forecast_idx
  on core.model_performance(forecast_run_id);
create index if not exists model_performance_model_idx
  on core.model_performance(model_id, model_version);
create index if not exists champion_model_current_idx
  on core.champion_model(item_id, selected_at desc, champion_model_id desc);
create index if not exists champion_model_backtest_idx
  on core.champion_model(backtest_run_id);
create index if not exists champion_model_forecast_idx
  on core.champion_model(forecast_run_id);
create index if not exists champion_model_model_idx
  on core.champion_model(model_id, model_version);
create index if not exists champion_model_selected_by_idx
  on core.champion_model(selected_by);
create index if not exists champion_selection_log_lookup_idx
  on core.champion_selection_log(item_id, selected_at desc);
create index if not exists champion_selection_log_backtest_idx
  on core.champion_selection_log(backtest_run_id);
create index if not exists champion_selection_log_selected_by_idx
  on core.champion_selection_log(selected_by);
create index if not exists forecast_run_setting_idx
  on core.forecast_run(forecast_setting_key);
create index if not exists forecast_run_triggered_by_idx
  on core.forecast_run(triggered_by);
create index if not exists forecast_setting_baseline_idx
  on core.forecast_setting(baseline_model_id, baseline_model_version);

drop trigger if exists model_config_set_updated_at on core.model_config;
create trigger model_config_set_updated_at before update on core.model_config
for each row execute function core.set_updated_at();
drop trigger if exists forecast_result_set_updated_at on core.forecast_result;
create trigger forecast_result_set_updated_at before update on core.forecast_result
for each row execute function core.set_updated_at();
drop trigger if exists backtest_run_set_updated_at on core.backtest_run;
create trigger backtest_run_set_updated_at before update on core.backtest_run
for each row execute function core.set_updated_at();

-- Forecast Result를 저장하는 STEP 6 쪽에서 사용할 수 있는 관리자 전용 upsert입니다.
-- 이 함수는 모델을 재실행하지 않고 저장 결과만 교체합니다.
create or replace function core.save_forecast_result(
  p_forecast_run_id uuid,
  p_rows jsonb
)
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_row jsonb;
  v_count integer := 0;
  v_run core.forecast_run%rowtype;
begin
  if not (select core.is_admin()) then
    raise exception 'ADMIN_REQUIRED' using errcode = '42501';
  end if;
  if jsonb_typeof(p_rows) <> 'array' then
    raise exception 'RESULT_ROWS_MUST_BE_ARRAY' using errcode = '22023';
  end if;
  select * into v_run from core.forecast_run where forecast_run_id = p_forecast_run_id for update;
  if not found then raise exception 'FORECAST_RUN_NOT_FOUND'; end if;
  if v_run.status <> 'READY' or v_run.stale then raise exception 'FORECAST_RUN_NOT_READY'; end if;

  for v_row in select value from jsonb_array_elements(p_rows) loop
    insert into core.forecast_result (
      forecast_run_id, model_id, model_version, item_id, forecast_date,
      forecast_value, p50, p80, p90, prediction_lower, prediction_upper, result_reason_code
    ) values (
      p_forecast_run_id,
      nullif(v_row ->> 'model_id', ''),
      nullif(v_row ->> 'model_version', ''),
      nullif(v_row ->> 'item_id', ''),
      (v_row ->> 'forecast_date')::date,
      nullif(v_row ->> 'forecast_value', '')::numeric,
      nullif(v_row ->> 'p50', '')::numeric,
      nullif(v_row ->> 'p80', '')::numeric,
      nullif(v_row ->> 'p90', '')::numeric,
      nullif(v_row ->> 'prediction_lower', '')::numeric,
      nullif(v_row ->> 'prediction_upper', '')::numeric,
      nullif(v_row ->> 'result_reason_code', '')
    )
    on conflict (forecast_run_id, model_id, model_version, item_id, forecast_date) do update
      set forecast_value = excluded.forecast_value,
          p50 = excluded.p50,
          p80 = excluded.p80,
          p90 = excluded.p90,
          prediction_lower = excluded.prediction_lower,
          prediction_upper = excluded.prediction_upper,
          result_reason_code = excluded.result_reason_code,
          updated_at = now();
    v_count := v_count + 1;
  end loop;
  return v_count;
end;
$$;

create or replace function core.run_backtest(
  p_forecast_run_id uuid,
  p_metric text default null
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_forecast_run core.forecast_run%rowtype;
  v_setting core.forecast_setting%rowtype;
  v_backtest_id uuid;
  v_metric text;
  v_item record;
  v_selected record;
  v_candidate_performance jsonb;
  v_candidate_count integer;
  v_valid_candidate_count integer;
begin
  if not (select core.is_admin()) then
    raise exception 'ADMIN_REQUIRED' using errcode = '42501';
  end if;

  select * into v_forecast_run
    from core.forecast_run
   where forecast_run_id = p_forecast_run_id;
  if not found then raise exception 'FORECAST_RUN_NOT_FOUND'; end if;
  if v_forecast_run.status <> 'READY' or v_forecast_run.stale then
    raise exception 'FORECAST_RUN_NOT_READY';
  end if;

  select * into v_setting
    from core.forecast_setting
   where setting_key = v_forecast_run.forecast_setting_key
     and active = true;
  if not found or v_setting.test_start is null or v_setting.test_end is null then
    raise exception 'TEST_PERIOD_NOT_CONFIGURED';
  end if;
  v_metric := upper(coalesce(nullif(trim(p_metric), ''), v_setting.champion_metric));
  if v_metric not in ('WAPE', 'MAPE', 'RMSE', 'MAE') then
    raise exception 'UNSUPPORTED_METRIC' using errcode = '22023';
  end if;

  insert into core.backtest_run (
    forecast_run_id, test_start, test_end, metric, status, triggered_by
  ) values (
    p_forecast_run_id, v_setting.test_start, v_setting.test_end, v_metric, 'RUNNING', (select auth.uid())
  ) returning backtest_run_id into v_backtest_id;

  begin
    with candidate_items as (
      select m.model_id, m.model_version, i.item_id
        from core.model_config as m
        cross join core.v_item_master as i
       where m.enabled = true
         and coalesce(i.is_active, 'Y') in ('Y', 'YES', 'TRUE', '1')
    ), actual_daily as (
      select t.item_id, t.use_date, sum(t.qty)::numeric as actual_qty
        from core.v_test_actual as t
       where t.use_date between v_setting.test_start and v_setting.test_end
       group by t.item_id, t.use_date
    ), forecast_daily as (
      select r.model_id, r.model_version, r.item_id, r.forecast_date,
             max(r.forecast_value)::numeric as forecast_value
        from core.forecast_result as r
       where r.forecast_run_id = p_forecast_run_id
         and r.forecast_date between v_setting.test_start and v_setting.test_end
       group by r.model_id, r.model_version, r.item_id, r.forecast_date
    ), dates as (
      select item_id, use_date as evaluation_date from actual_daily
      union
      select item_id, forecast_date from forecast_daily
    ), paired as (
      select c.model_id, c.model_version, c.item_id, d.evaluation_date,
             a.actual_qty, f.forecast_value
        from candidate_items as c
        left join dates as d on d.item_id = c.item_id
        left join actual_daily as a
          on a.item_id = c.item_id and a.use_date = d.evaluation_date
        left join forecast_daily as f
          on f.model_id = c.model_id
         and f.model_version = c.model_version
         and f.item_id = c.item_id
         and f.forecast_date = d.evaluation_date
    ), metrics as (
      select
        model_id,
        model_version,
        item_id,
        count(*) filter (where evaluation_date is not null)::integer as periods_total,
        count(*) filter (where actual_qty is not null)::integer as actual_periods,
        count(*) filter (where forecast_value is not null)::integer as forecast_periods,
        count(*) filter (where actual_qty is not null and forecast_value is not null)::integer as comparable_periods,
        sum(abs(actual_qty)) filter (where actual_qty is not null and forecast_value is not null) as actual_abs_sum,
        sum(abs(forecast_value - actual_qty)) filter (where actual_qty is not null and forecast_value is not null)
          / nullif(sum(abs(actual_qty)) filter (where actual_qty is not null and forecast_value is not null), 0) as wape,
        avg(abs(forecast_value - actual_qty) / nullif(abs(actual_qty), 0))
          filter (where actual_qty is not null and forecast_value is not null and actual_qty <> 0) as mape,
        avg(forecast_value - actual_qty) filter (where actual_qty is not null and forecast_value is not null) as bias,
        sqrt(avg(power(forecast_value - actual_qty, 2)) filter (where actual_qty is not null and forecast_value is not null)) as rmse,
        avg(abs(forecast_value - actual_qty)) filter (where actual_qty is not null and forecast_value is not null) as mae
      from paired
      group by model_id, model_version, item_id
    ), selected as (
      select m.*, case v_metric
        when 'WAPE' then m.wape
        when 'MAPE' then m.mape
        when 'RMSE' then m.rmse
        when 'MAE' then m.mae
      end as metric_value,
      case
        when m.periods_total = 0 then 'NO_TEST_DATA'
        when m.actual_periods = 0 then 'ACTUAL_MISSING'
        when m.forecast_periods = 0 then 'FORECAST_MISSING'
        when m.comparable_periods = 0 then 'NO_COMPARABLE_PERIODS'
        when v_metric = 'WAPE' and m.actual_abs_sum = 0 then 'ACTUAL_SUM_ZERO'
        when v_metric = 'MAPE' and not exists (
          select 1 from paired p
           where p.model_id = m.model_id and p.model_version = m.model_version and p.item_id = m.item_id
             and p.actual_qty is not null and p.forecast_value is not null and p.actual_qty <> 0
        ) then 'MAPE_NO_NONZERO_ACTUAL'
        else null
      end as reason_code
      from metrics as m
    ), scored as (
      select s.*, b.metric_value as baseline_metric_value,
        case
          when b.metric_value is null or s.metric_value is null then null
          when b.metric_value = 0 then case when s.metric_value = 0 then 0::numeric else null end
          else round((1 - s.metric_value / b.metric_value), 6)
        end as baseline_improvement,
        case
          when s.metric_value is null then null
          else row_number() over (
            partition by s.item_id
            order by s.metric_value asc, abs(coalesce(s.bias, 0)) asc,
                     s.rmse nulls last, s.model_id asc, s.model_version asc
          )::integer
        end as metric_rank
      from selected as s
      cross join (select * from core.forecast_setting where setting_key = v_forecast_run.forecast_setting_key limit 1) as setting
      left join selected as b
        on b.item_id = s.item_id
       and b.model_id = setting.baseline_model_id
       and b.model_version = setting.baseline_model_version
    )
    insert into core.model_performance (
      backtest_run_id, forecast_run_id, model_id, model_version, item_id,
      test_start, test_end, metric, periods_total, actual_periods, forecast_periods,
      comparable_periods, actual_abs_sum, wape, mape, bias, rmse, mae, metric_value,
      baseline_improvement, rank, status, reason_code
    )
    select
      v_backtest_id, p_forecast_run_id, model_id, model_version, item_id,
      v_setting.test_start, v_setting.test_end, v_metric, periods_total, actual_periods, forecast_periods,
      comparable_periods, actual_abs_sum, wape, mape, bias, rmse, mae, metric_value,
      baseline_improvement, metric_rank,
      case when metric_value is null then 'CALCULATION_UNAVAILABLE' else 'VALID' end,
      reason_code
    from scored;

    for v_item in
      select distinct item_id from core.model_performance where backtest_run_id = v_backtest_id order by item_id
    loop
      select count(*)::integer,
             count(*) filter (where status = 'VALID')::integer
        into v_candidate_count, v_valid_candidate_count
        from core.model_performance
       where backtest_run_id = v_backtest_id and item_id = v_item.item_id;

      select p.model_id, p.model_version, p.metric_value, p.baseline_improvement
        into v_selected
        from core.model_performance as p
       where p.backtest_run_id = v_backtest_id
         and p.item_id = v_item.item_id
         and p.status = 'VALID'
       order by p.rank, abs(coalesce(p.bias, 0)), p.rmse nulls last, p.model_id, p.model_version
       limit 1;

      select coalesce(jsonb_agg(jsonb_build_object(
        'model_id', p.model_id,
        'model_version', p.model_version,
        'metric', p.metric,
        'metric_value', p.metric_value,
        'wape', p.wape,
        'mape', p.mape,
        'bias', p.bias,
        'rmse', p.rmse,
        'mae', p.mae,
        'baseline_improvement', p.baseline_improvement,
        'rank', p.rank,
        'status', p.status,
        'reason_code', p.reason_code
      ) order by p.rank nulls last, p.model_id, p.model_version), '[]'::jsonb)
        into v_candidate_performance
        from core.model_performance as p
       where p.backtest_run_id = v_backtest_id and p.item_id = v_item.item_id;

      insert into core.champion_selection_log (
        backtest_run_id, item_id, metric, selection_method, selected_model_id,
        selected_model_version, candidate_count, valid_candidate_count,
        selection_reason, reason_code, selected_by
      ) values (
        v_backtest_id, v_item.item_id, v_metric, 'AUTO',
        v_selected.model_id, v_selected.model_version,
        v_candidate_count, v_valid_candidate_count,
        case when v_selected.model_id is null
          then '사용 가능한 모델이 없어 Champion을 만들지 않았습니다.'
          else format('AUTO %s 최소값 · 동률이면 |Bias| · RMSE · 모델 ID 순', v_metric)
        end,
        case when v_selected.model_id is null then 'NO_VALID_CANDIDATE' else null end,
        (select auth.uid())
      );

      if v_selected.model_id is not null then
        insert into core.champion_model (
          item_id, model_id, model_version, metric, metric_value, baseline_improvement,
          backtest_run_id, forecast_run_id, candidate_performance,
          selection_method, selection_reason, selected_by
        ) values (
          v_item.item_id, v_selected.model_id, v_selected.model_version, v_metric,
          v_selected.metric_value, v_selected.baseline_improvement,
          v_backtest_id, p_forecast_run_id, v_candidate_performance,
          'AUTO', format('AUTO %s 최소값 · 동률이면 |Bias| · RMSE · 모델 ID 순', v_metric),
          (select auth.uid())
        );
      end if;
    end loop;

    update core.backtest_run
       set status = 'COMPLETED', completed_at = now(), updated_at = now()
     where backtest_run_id = v_backtest_id;
  exception when others then
    update core.backtest_run
       set status = 'FAILED', error_code = sqlstate || ':' || left(sqlerrm, 200), completed_at = now(), updated_at = now()
     where backtest_run_id = v_backtest_id;
  end;

  return v_backtest_id;
end;
$$;

create or replace function core.set_manual_champion(
  p_item_id text,
  p_model_id text,
  p_model_version text,
  p_reason text,
  p_backtest_run_id uuid default null
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_performance core.model_performance%rowtype;
  v_backtest core.backtest_run%rowtype;
  v_setting core.forecast_setting%rowtype;
  v_champion_id bigint;
  v_before jsonb;
  v_candidates jsonb;
  v_candidate_count integer;
  v_valid_candidate_count integer;
begin
  if not (select core.is_admin()) then
    raise exception 'ADMIN_REQUIRED' using errcode = '42501';
  end if;
  if nullif(trim(coalesce(p_reason, '')), '') is null then
    raise exception 'MANUAL_REASON_REQUIRED' using errcode = '22023';
  end if;

  select * into v_setting from core.forecast_setting where setting_key = 'DEFAULT' and active = true;
  if not found then raise exception 'FORECAST_SETTING_NOT_FOUND'; end if;

  if p_backtest_run_id is null then
    select b.* into v_backtest
      from core.backtest_run as b
      join core.model_performance as p on p.backtest_run_id = b.backtest_run_id
     where b.status = 'COMPLETED'
       and p.item_id = p_item_id
       and p.model_id = p_model_id
       and p.model_version = p_model_version
       and p.status = 'VALID'
     order by b.completed_at desc nulls last, b.started_at desc
     limit 1;
  else
    select * into v_backtest from core.backtest_run where backtest_run_id = p_backtest_run_id and status = 'COMPLETED';
  end if;
  if not found then raise exception 'BACKTEST_PERFORMANCE_NOT_FOUND'; end if;

  select * into v_performance
    from core.model_performance
   where backtest_run_id = v_backtest.backtest_run_id
     and item_id = p_item_id
     and model_id = p_model_id
     and model_version = p_model_version
     and status = 'VALID';
  if not found then raise exception 'CANDIDATE_PERFORMANCE_UNAVAILABLE'; end if;

  select to_jsonb(x) into v_before
    from (
      select item_id, model_id, model_version, metric, metric_value, selection_method,
             selection_reason, backtest_run_id, selected_at
        from core.champion_model
       where item_id = p_item_id
       order by selected_at desc, champion_model_id desc
       limit 1
    ) as x;

  select count(*)::integer, count(*) filter (where status = 'VALID')::integer
    into v_candidate_count, v_valid_candidate_count
    from core.model_performance where backtest_run_id = v_backtest.backtest_run_id and item_id = p_item_id;
  select coalesce(jsonb_agg(jsonb_build_object(
    'model_id', p.model_id, 'model_version', p.model_version, 'metric', p.metric,
    'metric_value', p.metric_value, 'wape', p.wape, 'mape', p.mape,
    'bias', p.bias, 'rmse', p.rmse, 'mae', p.mae,
    'baseline_improvement', p.baseline_improvement, 'rank', p.rank,
    'status', p.status, 'reason_code', p.reason_code
  ) order by p.rank nulls last, p.model_id, p.model_version), '[]'::jsonb)
    into v_candidates
    from core.model_performance as p
   where p.backtest_run_id = v_backtest.backtest_run_id and p.item_id = p_item_id;

  insert into core.champion_model (
    item_id, model_id, model_version, metric, metric_value, baseline_improvement,
    backtest_run_id, forecast_run_id, candidate_performance,
    selection_method, selection_reason, selected_by
  ) values (
    p_item_id, p_model_id, p_model_version, v_performance.metric, v_performance.metric_value,
    v_performance.baseline_improvement, v_backtest.backtest_run_id, v_backtest.forecast_run_id,
    v_candidates, 'MANUAL', trim(p_reason), (select auth.uid())
  ) returning champion_model_id into v_champion_id;

  insert into core.champion_selection_log (
    backtest_run_id, item_id, metric, selection_method, selected_model_id,
    selected_model_version, candidate_count, valid_candidate_count,
    selection_reason, selected_by
  ) values (
    v_backtest.backtest_run_id, p_item_id, v_performance.metric, 'MANUAL',
    p_model_id, p_model_version, v_candidate_count, v_valid_candidate_count,
    trim(p_reason), (select auth.uid())
  );

  insert into core.audit_log (actor, action, target_type, target_id, before, after)
  values (
    (select auth.uid()), 'CHAMPION_MANUAL_SELECTED', 'champion_model', p_item_id,
    v_before,
    jsonb_build_object(
      'model_id', p_model_id, 'model_version', p_model_version,
      'metric', v_performance.metric, 'metric_value', v_performance.metric_value,
      'reason', trim(p_reason), 'backtest_run_id', v_backtest.backtest_run_id
    )
  );
  return v_champion_id;
end;
$$;

drop view if exists analytics.v_model_comparison;
create view analytics.v_model_comparison with (security_invoker = true) as
with actual_daily as (
  select item_id, use_date, sum(qty)::numeric as actual_qty
    from core.v_test_actual
   group by item_id, use_date
), result_base as (
  select r.*, m.model_name
    from core.forecast_result as r
    left join core.model_config as m
      on m.model_id = r.model_id and m.model_version = r.model_version
), model_items as (
  select distinct forecast_run_id, model_id, model_version, item_id from result_base
), dates as (
  select forecast_run_id, model_id, model_version, item_id, forecast_date as evaluation_date from result_base
  union
  select mi.forecast_run_id, mi.model_id, mi.model_version, mi.item_id, a.use_date
    from model_items as mi
    join actual_daily as a on a.item_id = mi.item_id
)
select
  d.forecast_run_id,
  d.model_id,
  d.model_version,
  rb.model_name,
  d.item_id,
  d.evaluation_date as forecast_date,
  a.actual_qty,
  rb.forecast_value,
  rb.p50,
  rb.p80,
  rb.p90,
  rb.prediction_lower,
  rb.prediction_upper,
  case when a.actual_qty is null then 'ACTUAL_UNAVAILABLE' else 'ACTUAL_AVAILABLE' end as validation_status
from dates as d
left join actual_daily as a
  on a.item_id = d.item_id and a.use_date = d.evaluation_date
left join result_base as rb
  on rb.forecast_run_id = d.forecast_run_id
 and rb.model_id = d.model_id
 and rb.model_version = d.model_version
 and rb.item_id = d.item_id
 and rb.forecast_date = d.evaluation_date;

drop view if exists analytics.v_backtest_runs;
create view analytics.v_backtest_runs with (security_invoker = true) as
select b.backtest_run_id, b.forecast_run_id, b.test_start, b.test_end, b.metric,
       b.status, b.triggered_by, b.started_at, b.completed_at, b.error_code,
       b.created_at, b.updated_at, r.data_snapshot_at, r.stale, r.status as forecast_status
  from core.backtest_run as b
  join core.forecast_run as r on r.forecast_run_id = b.forecast_run_id;

drop view if exists analytics.v_forecast_runs;
create view analytics.v_forecast_runs with (security_invoker = true) as
select r.forecast_run_id, r.forecast_setting_key, r.data_snapshot_at, r.status, r.stale,
       r.stale_reason, r.stale_at, r.triggered_by, r.train_start, r.train_end,
       r.created_at, r.updated_at
  from core.forecast_run as r;

drop view if exists analytics.v_model_config;
create view analytics.v_model_config with (security_invoker = true) as
select model_id, model_version, model_name, description, enabled, is_baseline, created_at, updated_at
  from core.model_config;

drop view if exists analytics.v_model_performance;
create view analytics.v_model_performance with (security_invoker = true) as
select p.*, m.model_name
  from core.model_performance as p
  left join core.model_config as m
    on m.model_id = p.model_id and m.model_version = p.model_version;

drop view if exists analytics.v_champion_model;
create view analytics.v_champion_model with (security_invoker = true) as
select distinct on (c.item_id)
  c.champion_model_id, c.item_id, c.model_id, c.model_version, m.model_name,
  c.metric, c.metric_value, c.baseline_improvement, c.backtest_run_id,
  c.forecast_run_id, c.candidate_performance, c.selection_method,
  c.selection_reason, c.selected_by, c.selected_at
  from core.champion_model as c
  left join core.model_config as m
    on m.model_id = c.model_id and m.model_version = c.model_version
 order by c.item_id, c.selected_at desc, c.champion_model_id desc;

drop view if exists analytics.v_champion_selection_log;
create view analytics.v_champion_selection_log with (security_invoker = true) as
select * from core.champion_selection_log;

drop view if exists analytics.v_forecast_settings;
create view analytics.v_forecast_settings with (security_invoker = true) as
with item_counts as (
  select count(*) filter (where active = true) as active_item_policy_count
    from core.item_policy
), rule_counts as (
  select count(*) filter (where enabled = true) as enabled_outlier_rule_count,
         count(*) filter (where enabled = true and learning_excluded = true) as learning_excluded_rule_count
    from core.outlier_rule
)
select c.*, p.policy_key as default_policy_key, p.service_level as default_service_level,
       p.review_period_days as default_review_period_days, p.safety_buffer_days as default_safety_buffer_days,
       p.config_value as default_policy_value, ic.active_item_policy_count,
       rc.enabled_outlier_rule_count, rc.learning_excluded_rule_count,
       s.champion_metric, s.baseline_model_id, s.baseline_model_version
  from analytics.v_data_coverage as c
  left join core.policy_config as p on p.policy_key = 'DEFAULT' and p.active = true
  join core.forecast_setting as s on s.setting_key = c.setting_key
  cross join item_counts as ic
  cross join rule_counts as rc;

-- 신규 테이블은 anon에 열지 않고, authenticated는 RLS가 허용하는 범위에서 읽습니다.
alter table core.model_config enable row level security;
alter table core.forecast_result enable row level security;
alter table core.backtest_run enable row level security;
alter table core.model_performance enable row level security;
alter table core.champion_model enable row level security;
alter table core.champion_selection_log enable row level security;

drop policy if exists model_config_authenticated_select on core.model_config;
create policy model_config_authenticated_select on core.model_config
  for select to authenticated using ((select auth.uid()) is not null);
drop policy if exists model_config_admin_mutation on core.model_config;
drop policy if exists model_config_admin_insert on core.model_config;
drop policy if exists model_config_admin_update on core.model_config;
drop policy if exists model_config_admin_delete on core.model_config;
create policy model_config_admin_insert on core.model_config
  for insert to authenticated with check ((select core.is_admin()));
create policy model_config_admin_update on core.model_config
  for update to authenticated using ((select core.is_admin())) with check ((select core.is_admin()));
create policy model_config_admin_delete on core.model_config
  for delete to authenticated using ((select core.is_admin()));

drop policy if exists forecast_result_authenticated_select on core.forecast_result;
create policy forecast_result_authenticated_select on core.forecast_result
  for select to authenticated using ((select auth.uid()) is not null);
drop policy if exists forecast_result_admin_mutation on core.forecast_result;
drop policy if exists forecast_result_admin_insert on core.forecast_result;
drop policy if exists forecast_result_admin_update on core.forecast_result;
drop policy if exists forecast_result_admin_delete on core.forecast_result;
create policy forecast_result_admin_insert on core.forecast_result
  for insert to authenticated with check ((select core.is_admin()));
create policy forecast_result_admin_update on core.forecast_result
  for update to authenticated using ((select core.is_admin())) with check ((select core.is_admin()));
create policy forecast_result_admin_delete on core.forecast_result
  for delete to authenticated using ((select core.is_admin()));

drop policy if exists backtest_run_authenticated_select on core.backtest_run;
create policy backtest_run_authenticated_select on core.backtest_run
  for select to authenticated using ((select auth.uid()) is not null);
drop policy if exists model_performance_authenticated_select on core.model_performance;
create policy model_performance_authenticated_select on core.model_performance
  for select to authenticated using ((select auth.uid()) is not null);
drop policy if exists champion_model_authenticated_select on core.champion_model;
create policy champion_model_authenticated_select on core.champion_model
  for select to authenticated using ((select auth.uid()) is not null);
drop policy if exists champion_selection_log_authenticated_select on core.champion_selection_log;
create policy champion_selection_log_authenticated_select on core.champion_selection_log
  for select to authenticated using ((select auth.uid()) is not null);

grant select on core.model_config, core.forecast_result, core.backtest_run,
  core.model_performance, core.champion_model, core.champion_selection_log to authenticated;
grant insert, update, delete on core.model_config, core.forecast_result to authenticated;
grant execute on function core.save_forecast_result(uuid, jsonb) to authenticated;
grant execute on function core.run_backtest(uuid, text) to authenticated;
grant execute on function core.set_manual_champion(text, text, text, text, uuid) to authenticated;

revoke all on schema core, analytics from anon;
revoke all on core.model_config, core.forecast_result, core.backtest_run,
  core.model_performance, core.champion_model, core.champion_selection_log from anon;
revoke all on analytics.v_model_comparison, analytics.v_backtest_runs, analytics.v_forecast_runs,
  analytics.v_model_config, analytics.v_model_performance, analytics.v_champion_model,
  analytics.v_champion_selection_log from anon;
revoke all on function core.save_forecast_result(uuid, jsonb) from public;
revoke all on function core.run_backtest(uuid, text) from public;
revoke all on function core.set_manual_champion(text, text, text, text, uuid) from public;
grant select on analytics.v_model_comparison, analytics.v_backtest_runs, analytics.v_forecast_runs,
  analytics.v_model_config, analytics.v_model_performance, analytics.v_champion_model,
  analytics.v_champion_selection_log to authenticated;

notify pgrst, 'reload schema';
