-- STEP 4: CSV/Excel 적재 staging, 검증 오류, 이력, rollback 구조

create schema if not exists core;

create table if not exists core.upload_batch (
  batch_id uuid primary key default gen_random_uuid(),
  file_name text not null,
  import_type text not null,
  import_mode text not null,
  total_rows integer not null default 0,
  success_rows integer not null default 0,
  warning_rows integer not null default 0,
  error_rows integer not null default 0,
  status text not null default 'STAGED',
  uploaded_by uuid not null references auth.users(id),
  uploaded_at timestamptz not null default now(),
  imported_at timestamptz,
  rolled_back_at timestamptz,
  replace_snapshot_at timestamptz,
  error_message text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint upload_batch_import_type_ck check (import_type in (
    'usage_history', 'inventory', 'item_master', 'supplier_master',
    'purchase_order', 'goods_receipt', 'sales_order',
    'business_event', 'item_substitute'
  )),
  constraint upload_batch_import_mode_ck check (import_mode in ('append', 'upsert', 'replace')),
  constraint upload_batch_status_ck check (status in (
    'STAGED', 'VALIDATING', 'VALIDATED', 'VALIDATED_WITH_ERRORS',
    'IMPORTING', 'IMPORTED', 'ROLLED_BACK', 'FAILED'
  )),
  constraint upload_batch_counts_ck check (
    total_rows >= 0 and success_rows >= 0 and warning_rows >= 0 and error_rows >= 0
  )
);

create table if not exists core.import_staging (
  staging_id bigint generated by default as identity primary key,
  batch_id uuid not null references core.upload_batch(batch_id) on delete cascade,
  row_number integer not null,
  original_data jsonb not null,
  mapped_data jsonb,
  validation_status text not null default 'PENDING',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (batch_id, row_number),
  constraint import_staging_row_number_ck check (row_number > 1),
  constraint import_staging_status_ck check (validation_status in ('PENDING', 'SUCCESS', 'WARNING', 'ERROR'))
);

create table if not exists core.column_mapping (
  mapping_id bigint generated by default as identity primary key,
  import_type text not null,
  source_column text not null,
  target_field text not null,
  created_by uuid references auth.users(id) on delete set null,
  usage_count integer not null default 1,
  last_used_at timestamptz not null default now(),
  unique (import_type, source_column, target_field)
);

create table if not exists core.validation_error (
  error_id bigint generated by default as identity primary key,
  batch_id uuid not null references core.upload_batch(batch_id) on delete cascade,
  staging_id bigint references core.import_staging(staging_id) on delete cascade,
  row_number integer not null,
  field_name text,
  error_code text not null,
  error_message text not null,
  severity text not null,
  original_value text,
  created_at timestamptz not null default now(),
  constraint validation_error_severity_ck check (severity in ('WARNING', 'ERROR'))
);

create table if not exists core.import_backup (
  backup_id bigint generated by default as identity primary key,
  batch_id uuid not null references core.upload_batch(batch_id) on delete cascade,
  target_table text not null,
  source_record_id text,
  previous_data jsonb not null,
  created_at timestamptz not null default now()
);

-- 현재 프로젝트에는 Forecast Run 테이블이 없어 STEP 6에서 사용할 최소 계약을 준비합니다.
-- 결과 자체는 삭제하지 않고 새 수요 적재 시 stale만 표시합니다.
create table if not exists core.forecast_run (
  forecast_run_id uuid primary key default gen_random_uuid(),
  data_snapshot_at timestamptz not null,
  status text not null default 'READY',
  stale boolean not null default false,
  stale_reason text,
  stale_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint forecast_run_status_ck check (status in ('READY', 'STALE', 'FAILED'))
);

create index if not exists upload_batch_uploaded_at_idx on core.upload_batch(uploaded_at desc);
create index if not exists upload_batch_status_idx on core.upload_batch(status);
create index if not exists import_staging_batch_idx on core.import_staging(batch_id, row_number);
create index if not exists validation_error_batch_idx on core.validation_error(batch_id, severity, row_number);
create index if not exists validation_error_staging_idx on core.validation_error(staging_id);
create index if not exists import_backup_batch_idx on core.import_backup(batch_id, target_table);
create index if not exists forecast_run_snapshot_idx on core.forecast_run(data_snapshot_at desc);
create index if not exists upload_batch_uploaded_by_idx on core.upload_batch(uploaded_by);
create index if not exists column_mapping_created_by_idx on core.column_mapping(created_by);

drop trigger if exists upload_batch_set_updated_at on core.upload_batch;
create trigger upload_batch_set_updated_at before update on core.upload_batch for each row execute function core.set_updated_at();
drop trigger if exists import_staging_set_updated_at on core.import_staging;
create trigger import_staging_set_updated_at before update on core.import_staging for each row execute function core.set_updated_at();
drop trigger if exists forecast_run_set_updated_at on core.forecast_run;
create trigger forecast_run_set_updated_at before update on core.forecast_run for each row execute function core.set_updated_at();

-- 검증 단계에서 supplier master 존재 여부를 확인할 수 있는 정제 view입니다.
create or replace view core.v_supplier_master as
select
  nullif(trim("공급업체코드"), '') as supplier_id,
  nullif(trim("공급업체명"), '') as supplier_name,
  nullif(trim("국가"), '') as country,
  nullif(trim("표준리드타임(일)"), '') as standard_lead_time,
  nullif(trim("사용여부"), '') as is_active
from raw.supplier_master
where nullif(trim("공급업체코드"), '') is not null;

-- import type별 실제 raw 대상 컬럼. identity PK는 insert 시 제외하거나 rollback 복구 시 포함합니다.
create or replace function core.import_target_columns(p_import_type text, p_include_identity boolean default false)
returns text[]
language sql
immutable
set search_path = ''
as $$
  select case
    when p_import_type = 'usage_history' then array['usage_id','item_id','use_date','qty','warehouse','note','batch_id','source_type','loaded_at','source_record_id']::text[]
    when p_import_type = 'inventory' then array['품목코드','창고','현재고','기준일자','안전재고','batch_id','source_type','loaded_at','source_record_id']::text[]
    when p_import_type = 'item_master' then array['품목코드','품목명','품목구분','단위','표준단가','사용여부','supplier_id','batch_id','source_type','loaded_at','source_record_id']::text[]
    when p_import_type = 'supplier_master' then array['공급업체코드','공급업체명','국가','표준리드타임(일)','담당자','사용여부','batch_id','source_type','loaded_at','source_record_id']::text[]
    when p_import_type = 'purchase_order' then array['발주번호','발주일','공급업체','품목코드','발주수량','단가','납기예정일','발주담당','batch_id','source_type','loaded_at','source_record_id']::text[]
    when p_import_type = 'goods_receipt' then array['입고번호','발주번호','품목코드','입고수량','입고일','입고창고','batch_id','source_type','loaded_at','source_record_id']::text[]
    when p_import_type = 'sales_order' then case when p_include_identity then array['id','sales_order_no','line_no','order_date','item_id','supplier_id','customer_id','ordered_qty','requested_delivery_date','status','batch_id','source_type','loaded_at','source_record_id']::text[] else array['sales_order_no','line_no','order_date','item_id','supplier_id','customer_id','ordered_qty','requested_delivery_date','status','batch_id','source_type','loaded_at','source_record_id']::text[] end
    when p_import_type = 'business_event' then case when p_include_identity then array['id','event_id','event_type','event_date','item_id','quantity','description','status','batch_id','source_type','loaded_at','source_record_id']::text[] else array['event_id','event_type','event_date','item_id','quantity','description','status','batch_id','source_type','loaded_at','source_record_id']::text[] end
    when p_import_type = 'item_substitute' then case when p_include_identity then array['id','item_id','substitute_item_id','priority','valid_from','valid_to','reason','active','batch_id','source_type','loaded_at','source_record_id']::text[] else array['item_id','substitute_item_id','priority','valid_from','valid_to','reason','active','batch_id','source_type','loaded_at','source_record_id']::text[] end
    else null
  end;
$$;

-- 검증 완료된 JSON 행을 whitelist된 raw 테이블에만 저장합니다.
-- 이 함수는 admin 확인을 다시 하고, replace/upsert의 이전 데이터도 backup합니다.
create or replace function core.import_batch_rows(p_batch_id uuid, p_rows jsonb)
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_batch core.upload_batch%rowtype;
  v_target text;
  v_columns text[];
  v_columns_sql text;
  v_select_sql text;
  v_row jsonb;
  v_previous jsonb;
  v_source_record_id text;
  v_imported integer := 0;
begin
  if not (select core.is_admin()) then
    raise exception 'ADMIN_REQUIRED' using errcode = '42501';
  end if;

  select * into v_batch
    from core.upload_batch
   where batch_id = p_batch_id
   for update;
  if not found then raise exception 'BATCH_NOT_FOUND'; end if;
  if v_batch.status not in ('VALIDATED', 'VALIDATED_WITH_ERRORS', 'IMPORTING') then
    raise exception 'BATCH_NOT_READY';
  end if;
  if jsonb_typeof(p_rows) <> 'array' then raise exception 'ROWS_MUST_BE_ARRAY'; end if;

  v_target := case v_batch.import_type
    when 'usage_history' then 'usage_history'
    when 'inventory' then 'inventory'
    when 'item_master' then 'item_master'
    when 'supplier_master' then 'supplier_master'
    when 'purchase_order' then 'purchase_order'
    when 'goods_receipt' then 'goods_receipt'
    when 'sales_order' then 'sales_order'
    when 'business_event' then 'business_event'
    when 'item_substitute' then 'item_substitute'
    else null
  end;
  if v_target is null then raise exception 'IMPORT_TYPE_NOT_ALLOWED'; end if;

  if v_batch.import_mode = 'replace' and v_batch.replace_snapshot_at is null then
    execute format(
      'insert into core.import_backup(batch_id,target_table,source_record_id,previous_data)
       select $1,$2,source_record_id,to_jsonb(t) from raw.%I t', v_target
    ) using p_batch_id, v_target;
    execute format('delete from raw.%I', v_target);
    update core.upload_batch set replace_snapshot_at = now(), status = 'IMPORTING', updated_at = now() where batch_id = p_batch_id;
  end if;

  v_columns := core.import_target_columns(v_batch.import_type, false);
  v_columns_sql := array_to_string(array(select quote_ident(c) from unnest(v_columns) as c), ',');
  v_select_sql := array_to_string(array(select format('(r).%I', c) from unnest(v_columns) as c), ',');

  for v_row in select value from jsonb_array_elements(p_rows) loop
    v_source_record_id := nullif(v_row ->> 'source_record_id', '');
    if v_source_record_id is null then raise exception 'SOURCE_RECORD_ID_REQUIRED'; end if;
    if not exists (
      select 1
        from core.import_staging as s
       where s.batch_id = p_batch_id
         and s.validation_status in ('SUCCESS', 'WARNING')
         and s.mapped_data = v_row
    ) then
      raise exception 'ROW_NOT_VALIDATED' using errcode = '22023';
    end if;

    if v_batch.import_mode = 'upsert' then
      execute format(
        'select coalesce(jsonb_agg(to_jsonb(t)), ''[]''::jsonb) from raw.%I t where source_record_id = $1', v_target
      ) into v_previous using v_source_record_id;
      if jsonb_array_length(v_previous) > 0 then
        insert into core.import_backup(batch_id,target_table,source_record_id,previous_data)
        select p_batch_id, v_target, v_source_record_id, jsonb_array_elements(v_previous);
      end if;
      execute format('delete from raw.%I where source_record_id = $1', v_target) using v_source_record_id;
    end if;

    execute format(
      'insert into raw.%I (%s)
       select %s from jsonb_populate_record(null::raw.%I, $1) as r',
      v_target, v_columns_sql, v_select_sql, v_target
    ) using v_row;
    v_imported := v_imported + 1;
  end loop;

  if v_batch.import_type in ('usage_history','sales_order','business_event','item_substitute') then
    update core.forecast_run
       set stale = true,
           status = 'STALE',
           stale_reason = coalesce(stale_reason, 'NEW_FILE_UPLOAD:' || p_batch_id::text),
           stale_at = coalesce(stale_at, now()),
           updated_at = now()
     where stale = false;
  end if;
  return v_imported;
end;
$$;

-- batch_id 범위만 제거하고, upsert/replace의 이전 snapshot은 복구합니다.
create or replace function core.rollback_batch(p_batch_id uuid)
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_batch core.upload_batch%rowtype;
  v_target text;
  v_columns text[];
  v_columns_sql text;
  v_select_sql text;
  v_backup record;
  v_deleted integer := 0;
begin
  if not (select core.is_admin()) then
    raise exception 'ADMIN_REQUIRED' using errcode = '42501';
  end if;
  select * into v_batch from core.upload_batch where batch_id = p_batch_id for update;
  if not found then raise exception 'BATCH_NOT_FOUND'; end if;
  if v_batch.status = 'ROLLED_BACK' then return 0; end if;
  if v_batch.status not in ('IMPORTED','FAILED','IMPORTING') then raise exception 'BATCH_NOT_IMPORTED'; end if;

  v_target := case v_batch.import_type
    when 'usage_history' then 'usage_history'
    when 'inventory' then 'inventory'
    when 'item_master' then 'item_master'
    when 'supplier_master' then 'supplier_master'
    when 'purchase_order' then 'purchase_order'
    when 'goods_receipt' then 'goods_receipt'
    when 'sales_order' then 'sales_order'
    when 'business_event' then 'business_event'
    when 'item_substitute' then 'item_substitute'
    else null
  end;
  if v_target is null then raise exception 'IMPORT_TYPE_NOT_ALLOWED'; end if;

  execute format('delete from raw.%I where batch_id = $1', v_target) using p_batch_id;
  get diagnostics v_deleted = row_count;

  if v_batch.import_mode in ('upsert','replace') then
    v_columns := core.import_target_columns(v_batch.import_type, true);
    v_columns_sql := array_to_string(array(select quote_ident(c) from unnest(v_columns) as c), ',');
    v_select_sql := array_to_string(array(select format('(r).%I', c) from unnest(v_columns) as c), ',');
    for v_backup in select previous_data from core.import_backup where batch_id = p_batch_id order by backup_id loop
      execute format(
        'insert into raw.%I (%s)
         select %s from jsonb_populate_record(null::raw.%I, $1) as r',
        v_target, v_columns_sql, v_select_sql, v_target
      ) using v_backup.previous_data;
    end loop;
  end if;

  update core.upload_batch
     set status = 'ROLLED_BACK', rolled_back_at = now(), updated_at = now()
   where batch_id = p_batch_id;
  return v_deleted;
end;
$$;

-- 관리자만 staging/이력/검증 오류와 설정을 다룹니다.
alter table core.upload_batch enable row level security;
alter table core.import_staging enable row level security;
alter table core.column_mapping enable row level security;
alter table core.validation_error enable row level security;
alter table core.import_backup enable row level security;
alter table core.forecast_run enable row level security;

create policy upload_batch_admin_select on core.upload_batch for select to authenticated using ((select core.is_admin()));
create policy upload_batch_admin_insert on core.upload_batch for insert to authenticated with check ((select core.is_admin()) and uploaded_by = (select auth.uid()));
create policy upload_batch_admin_update on core.upload_batch for update to authenticated using ((select core.is_admin())) with check ((select core.is_admin()));

create policy import_staging_admin_select on core.import_staging for select to authenticated using ((select core.is_admin()));
create policy import_staging_admin_insert on core.import_staging for insert to authenticated with check ((select core.is_admin()));
create policy import_staging_admin_update on core.import_staging for update to authenticated using ((select core.is_admin())) with check ((select core.is_admin()));
create policy import_staging_admin_delete on core.import_staging for delete to authenticated using ((select core.is_admin()));

create policy column_mapping_admin_all on core.column_mapping for all to authenticated using ((select core.is_admin())) with check ((select core.is_admin()));
create policy validation_error_admin_select on core.validation_error for select to authenticated using ((select core.is_admin()));
create policy validation_error_admin_insert on core.validation_error for insert to authenticated with check ((select core.is_admin()));
create policy validation_error_admin_delete on core.validation_error for delete to authenticated using ((select core.is_admin()));
create policy import_backup_admin_select on core.import_backup for select to authenticated using ((select core.is_admin()));
create policy forecast_run_authenticated_select on core.forecast_run for select to authenticated using ((select auth.uid()) is not null);
create policy forecast_run_admin_update on core.forecast_run for update to authenticated using ((select core.is_admin())) with check ((select core.is_admin()));

revoke all on schema core from anon;
revoke all on core.upload_batch, core.import_staging, core.column_mapping, core.validation_error, core.import_backup, core.forecast_run from anon;
grant usage on schema core to authenticated;
grant select, insert, update on core.upload_batch to authenticated;
grant select, insert, update, delete on core.import_staging to authenticated;
grant select, insert, update, delete on core.column_mapping to authenticated;
grant select, insert, delete on core.validation_error to authenticated;
grant select on core.import_backup to authenticated;
grant select, update on core.forecast_run to authenticated;
grant select on core.v_supplier_master to authenticated;
grant execute on function core.import_batch_rows(uuid,jsonb) to authenticated;
grant execute on function core.rollback_batch(uuid) to authenticated;
revoke all on function core.import_target_columns(text,boolean) from public;
revoke all on function core.import_batch_rows(uuid,jsonb) from public;
revoke all on function core.rollback_batch(uuid) from public;

alter default privileges in schema core revoke all on tables from anon;
notify pgrst, 'reload schema';
