-- STEP 3: 파일/API 적재 구조와 Forecast 학습·검증 기간을 분리합니다.
-- raw는 원본 보관용, core는 운영 기준과 격리된 데이터셋, analytics는 조회용입니다.

create schema if not exists raw;
create schema if not exists core;
create schema if not exists analytics;

-- 기존 raw 입력 테이블에는 원본 행을 변경하지 않고 적재 추적 컬럼만 추가합니다.
alter table if exists raw.shipment_log add column if not exists batch_id uuid;
alter table if exists raw.shipment_log add column if not exists source_type text;
alter table if exists raw.shipment_log add column if not exists loaded_at timestamptz;
alter table if exists raw.shipment_log add column if not exists source_record_id text;

alter table if exists raw.supplier_master add column if not exists batch_id uuid;
alter table if exists raw.supplier_master add column if not exists source_type text;
alter table if exists raw.supplier_master add column if not exists loaded_at timestamptz;
alter table if exists raw.supplier_master add column if not exists source_record_id text;

alter table if exists raw.item_master add column if not exists batch_id uuid;
alter table if exists raw.item_master add column if not exists source_type text;
alter table if exists raw.item_master add column if not exists loaded_at timestamptz;
alter table if exists raw.item_master add column if not exists source_record_id text;

alter table if exists raw.inventory add column if not exists batch_id uuid;
alter table if exists raw.inventory add column if not exists source_type text;
alter table if exists raw.inventory add column if not exists loaded_at timestamptz;
alter table if exists raw.inventory add column if not exists source_record_id text;

alter table if exists raw.usage_history add column if not exists batch_id uuid;
alter table if exists raw.usage_history add column if not exists source_type text;
alter table if exists raw.usage_history add column if not exists loaded_at timestamptz;
alter table if exists raw.usage_history add column if not exists source_record_id text;

alter table if exists raw.forecast add column if not exists batch_id uuid;
alter table if exists raw.forecast add column if not exists source_type text;
alter table if exists raw.forecast add column if not exists loaded_at timestamptz;
alter table if exists raw.forecast add column if not exists source_record_id text;

alter table if exists raw.goods_receipt add column if not exists batch_id uuid;
alter table if exists raw.goods_receipt add column if not exists source_type text;
alter table if exists raw.goods_receipt add column if not exists loaded_at timestamptz;
alter table if exists raw.goods_receipt add column if not exists source_record_id text;

alter table if exists raw.purchase_order add column if not exists batch_id uuid;
alter table if exists raw.purchase_order add column if not exists source_type text;
alter table if exists raw.purchase_order add column if not exists loaded_at timestamptz;
alter table if exists raw.purchase_order add column if not exists source_record_id text;

create table if not exists raw.business_event (
  id bigint generated by default as identity primary key,
  event_id text,
  event_type text,
  event_date date,
  item_id text,
  quantity numeric,
  description text,
  status text,
  batch_id uuid,
  source_type text,
  loaded_at timestamptz,
  source_record_id text
);

create table if not exists raw.sales_order (
  id bigint generated by default as identity primary key,
  sales_order_no text,
  line_no text,
  order_date date,
  item_id text,
  supplier_id text,
  customer_id text,
  ordered_qty numeric,
  requested_delivery_date date,
  status text,
  batch_id uuid,
  source_type text,
  loaded_at timestamptz,
  source_record_id text
);

create table if not exists raw.item_substitute (
  id bigint generated by default as identity primary key,
  item_id text,
  substitute_item_id text,
  priority integer,
  valid_from date,
  valid_to date,
  reason text,
  active boolean,
  batch_id uuid,
  source_type text,
  loaded_at timestamptz,
  source_record_id text
);

create index if not exists shipment_log_batch_idx on raw.shipment_log(batch_id);
create index if not exists supplier_master_batch_idx on raw.supplier_master(batch_id);
create index if not exists item_master_batch_idx on raw.item_master(batch_id);
create index if not exists inventory_batch_idx on raw.inventory(batch_id);
create index if not exists usage_history_batch_idx on raw.usage_history(batch_id);
create index if not exists forecast_batch_idx on raw.forecast(batch_id);
create index if not exists goods_receipt_batch_idx on raw.goods_receipt(batch_id);
create index if not exists purchase_order_batch_idx on raw.purchase_order(batch_id);
create index if not exists business_event_batch_idx on raw.business_event(batch_id);
create index if not exists sales_order_batch_idx on raw.sales_order(batch_id);
create index if not exists item_substitute_batch_idx on raw.item_substitute(batch_id);

create table if not exists core.policy_config (
  policy_key text primary key,
  service_level numeric(7, 4),
  review_period_days integer,
  safety_buffer_days numeric(10, 2),
  config_value jsonb not null default '{}'::jsonb,
  description text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint policy_config_service_level_ck check (service_level is null or service_level > 0 and service_level <= 1),
  constraint policy_config_review_period_ck check (review_period_days is null or review_period_days >= 0),
  constraint policy_config_safety_buffer_ck check (safety_buffer_days is null or safety_buffer_days >= 0)
);

create table if not exists core.outlier_rule (
  rule_id bigint generated by default as identity primary key,
  rule_code text not null unique,
  rule_type text not null,
  rule_name text not null,
  enabled boolean not null default true,
  learning_excluded boolean not null default true,
  priority integer not null default 100,
  condition jsonb not null default '{}'::jsonb,
  description text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint outlier_rule_type_ck check (rule_type in ('PROJECT', 'RETURN', 'DUPLICATE', 'OTHER')),
  constraint outlier_rule_priority_ck check (priority >= 0)
);

create table if not exists core.item_policy (
  item_id text primary key,
  moq numeric(18, 3),
  pack_size numeric(18, 3),
  item_grade text,
  service_level numeric(7, 4),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint item_policy_moq_ck check (moq is null or moq >= 0),
  constraint item_policy_pack_size_ck check (pack_size is null or pack_size > 0),
  constraint item_policy_service_level_ck check (service_level is null or service_level > 0 and service_level <= 1)
);

create table if not exists core.forecast_setting (
  setting_key text primary key default 'DEFAULT',
  train_start date,
  train_end date,
  test_start date,
  test_end date,
  granularity text not null default 'DAILY',
  description text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint forecast_setting_granularity_ck check (granularity in ('DAILY', 'WEEKLY', 'MONTHLY')),
  constraint forecast_setting_train_range_ck check (train_start is null or train_end is null or train_start <= train_end),
  constraint forecast_setting_test_range_ck check (test_start is null or test_end is null or test_start <= test_end),
  constraint forecast_setting_order_ck check (train_end is null or test_start is null or train_end < test_start)
);

drop trigger if exists policy_config_set_updated_at on core.policy_config;
create trigger policy_config_set_updated_at before update on core.policy_config for each row execute function core.set_updated_at();
drop trigger if exists outlier_rule_set_updated_at on core.outlier_rule;
create trigger outlier_rule_set_updated_at before update on core.outlier_rule for each row execute function core.set_updated_at();
drop trigger if exists item_policy_set_updated_at on core.item_policy;
create trigger item_policy_set_updated_at before update on core.item_policy for each row execute function core.set_updated_at();
drop trigger if exists forecast_setting_set_updated_at on core.forecast_setting;
create trigger forecast_setting_set_updated_at before update on core.forecast_setting for each row execute function core.set_updated_at();

insert into core.policy_config (policy_key, description)
values ('DEFAULT', '기본 운영 정책. 실제 서비스 레벨과 운영일수는 관리자가 설정합니다.')
on conflict (policy_key) do nothing;

insert into core.outlier_rule (rule_code, rule_type, rule_name, priority, condition, description)
values
  ('PROJECT_DEMAND', 'PROJECT', '프로젝트성 수요', 10, '{"note_contains":"프로젝트"}'::jsonb, '프로젝트성 수요는 학습에서 제외'),
  ('RETURN_QTY', 'RETURN', '반품 수량', 20, '{"negative_qty":true}'::jsonb, '음수 사용량은 학습에서 제외'),
  ('DUPLICATE_ROW', 'DUPLICATE', '중복 행', 30, '{"partition":"item_id,use_date,qty,warehouse,note"}'::jsonb, '동일 원본 행의 두 번째 이후 행은 학습에서 제외')
on conflict (rule_code) do nothing;

insert into core.forecast_setting (setting_key, granularity, description)
values ('DEFAULT', 'DAILY', '초기 데이터 기준 80% 학습 / 20% 검증. 관리자가 기간을 조정할 수 있습니다.')
on conflict (setting_key) do nothing;

-- 날짜를 애플리케이션 코드에 고정하지 않고 현재 적재 데이터의 경계로 초기값을 만듭니다.
with bounds as (
  select
    min(use_date) as data_start,
    max(use_date) as data_end,
    min(use_date) + greatest(1, floor((max(use_date) - min(use_date)) * 0.8)::integer) as split_date
  from raw.usage_history
  where use_date is not null
)
update core.forecast_setting as f
   set train_start = b.data_start,
       train_end = b.split_date - 1,
       test_start = b.split_date,
       test_end = b.data_end,
       updated_at = now()
  from bounds as b
 where f.setting_key = 'DEFAULT'
   and f.train_start is null
   and b.data_start is not null
   and b.data_end > b.data_start;

-- Forecast와 Demand Profile의 입력 경계를 DB 설정값으로 고정합니다.
create or replace view core.v_train_demand as
select
  f.setting_key,
  u.usage_id,
  u.item_id,
  u.use_date,
  u.qty,
  u.warehouse,
  u.note,
  u.batch_id,
  u.source_type,
  u.loaded_at,
  u.source_record_id
from raw.usage_history as u
join core.forecast_setting as f
  on f.setting_key = 'DEFAULT'
 and f.active = true
where f.train_start is not null
  and f.train_end is not null
  and u.use_date between f.train_start and f.train_end;

create or replace view core.v_test_actual as
select
  f.setting_key,
  u.usage_id,
  u.item_id,
  u.use_date,
  u.qty,
  u.warehouse,
  u.note,
  u.batch_id,
  u.source_type,
  u.loaded_at,
  u.source_record_id
from raw.usage_history as u
join core.forecast_setting as f
  on f.setting_key = 'DEFAULT'
 and f.active = true
where f.test_start is not null
  and f.test_end is not null
  and u.use_date between f.test_start and f.test_end;

-- 실제 데이터 범위와 설정 범위를 한 줄에서 점검합니다.
create or replace view analytics.v_data_coverage as
with bounds as (
  select min(use_date) as data_start, max(use_date) as data_end
  from raw.usage_history
), settings as (
  select * from core.forecast_setting where setting_key = 'DEFAULT' limit 1
), counts as (
  select
    count(*) filter (where f.train_start is not null and f.train_end is not null and u.use_date between f.train_start and f.train_end) as train_row_count,
    count(*) filter (where f.test_start is not null and f.test_end is not null and u.use_date between f.test_start and f.test_end) as test_row_count,
    count(*) filter (where f.train_start is not null and f.train_end is not null and f.test_start is not null and f.test_end is not null and u.use_date between f.train_start and f.train_end and u.use_date between f.test_start and f.test_end) as overlap_row_count
  from raw.usage_history as u
  left join settings as f on true
)
select
  s.setting_key,
  b.data_start,
  b.data_end,
  s.train_start,
  s.train_end,
  s.test_start,
  s.test_end,
  s.granularity,
  c.train_row_count,
  c.test_row_count,
  c.overlap_row_count,
  (
    b.data_start is not null
    and b.data_end is not null
    and s.train_start is not null
    and s.train_end is not null
    and s.train_start >= b.data_start
    and s.train_end <= b.data_end
    and s.train_start <= s.train_end
    and c.train_row_count > 0
  ) as train_window_ok,
  (
    b.data_start is not null
    and b.data_end is not null
    and s.test_start is not null
    and s.test_end is not null
    and s.test_start >= b.data_start
    and s.test_end <= b.data_end
    and s.test_start <= s.test_end
    and c.test_row_count > 0
  ) as test_window_ok,
  (c.overlap_row_count = 0) as isolation_ok
from bounds as b
left join settings as s on true
cross join counts as c;

-- 관리자 화면이 한 번의 조회로 기간·격리·정책 상태를 확인하도록 하는 조회용 view입니다.
create or replace view analytics.v_forecast_settings as
with item_counts as (
  select count(*) filter (where active = true) as active_item_policy_count
  from core.item_policy
), rule_counts as (
  select
    count(*) filter (where enabled = true) as enabled_outlier_rule_count,
    count(*) filter (where enabled = true and learning_excluded = true) as learning_excluded_rule_count
  from core.outlier_rule
)
select
  c.*,
  p.policy_key as default_policy_key,
  p.service_level as default_service_level,
  p.review_period_days as default_review_period_days,
  p.safety_buffer_days as default_safety_buffer_days,
  p.config_value as default_policy_value,
  ic.active_item_policy_count,
  rc.enabled_outlier_rule_count,
  rc.learning_excluded_rule_count
from analytics.v_data_coverage as c
left join core.policy_config as p
  on p.policy_key = 'DEFAULT'
 and p.active = true
cross join item_counts as ic
cross join rule_counts as rc;

-- Demand Profile은 raw.usage_history를 직접 보지 않고 학습 view만 사용합니다.
-- 기존 평균/표준편차 계산식은 유지하고, DB outlier_rule로 제외 범위를 관리합니다.
create or replace view core.v_usage_effective as
with deduped as (
  select
    d.*,
    row_number() over (
      partition by upper(regexp_replace(coalesce(d.item_id, ''), '[\\s\\-_]', '', 'g')), d.use_date, d.qty, d.warehouse, d.note
      order by d.usage_id
    ) as duplicate_rank
  from core.v_train_demand as d
), filtered as (
  select d.*
  from deduped as d
  where not exists (
    select 1 from core.outlier_rule as r
    where r.enabled = true
      and r.learning_excluded = true
      and r.rule_type = 'DUPLICATE'
      and d.duplicate_rank > 1
  )
  and not exists (
    select 1 from core.outlier_rule as r
    where r.enabled = true
      and r.learning_excluded = true
      and r.rule_type = 'RETURN'
      and d.qty < 0
  )
  and not exists (
    select 1 from core.outlier_rule as r
    where r.enabled = true
      and r.learning_excluded = true
      and r.rule_type = 'PROJECT'
      and coalesce(r.condition ->> 'note_contains', '') <> ''
      and coalesce(d.note, '') ilike '%' || (r.condition ->> 'note_contains') || '%'
  )
), calc as (
  select
    upper(regexp_replace(f.item_id, '[\\s\\-_]', '', 'g')) as item_id,
    count(*) as valid_days,
    round(avg(f.qty), 2) as daily_usage_avg,
    round(stddev_samp(f.qty), 2) as daily_usage_sd
  from filtered as f
  where f.item_id is not null
    and f.qty is not null
  group by upper(regexp_replace(f.item_id, '[\\s\\-_]', '', 'g'))
)
select
  c.item_id,
  coalesce(p.valid_days::bigint, c.valid_days) as valid_days,
  coalesce(p.daily_usage_avg, c.daily_usage_avg) as daily_usage_avg,
  coalesce(p.daily_usage_sd, c.daily_usage_sd) as daily_usage_sd,
  round(coalesce(p.daily_usage_avg, c.daily_usage_avg), 2) as usage_used,
  round(coalesce(p.daily_usage_sd, c.daily_usage_sd) / nullif(coalesce(p.daily_usage_avg, c.daily_usage_avg), 0::numeric), 2) as cv,
  case when p.item_id is not null then '확정값' else '정제 기준' end as source
from calc as c
left join core.usage_profile as p on p.item_id = c.item_id;

-- raw는 Data API에서 직접 읽거나 쓸 수 없게 유지하고, 허용된 core/analytics view만 노출합니다.
revoke all on schema raw from anon, authenticated;
revoke all on all tables in schema raw from anon, authenticated;
alter default privileges in schema raw revoke all on tables from anon, authenticated;

alter table core.policy_config enable row level security;
alter table core.outlier_rule enable row level security;
alter table core.item_policy enable row level security;
alter table core.forecast_setting enable row level security;

drop policy if exists policy_config_select_authenticated on core.policy_config;
create policy policy_config_select_authenticated on core.policy_config
for select to authenticated using ((select auth.uid()) is not null);
drop policy if exists policy_config_admin_mutation on core.policy_config;
create policy policy_config_admin_mutation on core.policy_config
for all to authenticated using ((select core.is_admin())) with check ((select core.is_admin()));

drop policy if exists outlier_rule_select_authenticated on core.outlier_rule;
create policy outlier_rule_select_authenticated on core.outlier_rule
for select to authenticated using ((select auth.uid()) is not null);
drop policy if exists outlier_rule_admin_mutation on core.outlier_rule;
create policy outlier_rule_admin_mutation on core.outlier_rule
for all to authenticated using ((select core.is_admin())) with check ((select core.is_admin()));

drop policy if exists item_policy_select_authenticated on core.item_policy;
create policy item_policy_select_authenticated on core.item_policy
for select to authenticated using ((select auth.uid()) is not null);
drop policy if exists item_policy_admin_mutation on core.item_policy;
create policy item_policy_admin_mutation on core.item_policy
for all to authenticated using ((select core.is_admin())) with check ((select core.is_admin()));

drop policy if exists forecast_setting_select_authenticated on core.forecast_setting;
create policy forecast_setting_select_authenticated on core.forecast_setting
for select to authenticated using ((select auth.uid()) is not null);
drop policy if exists forecast_setting_admin_mutation on core.forecast_setting;
create policy forecast_setting_admin_mutation on core.forecast_setting
for all to authenticated using ((select core.is_admin())) with check ((select core.is_admin()));

grant usage on schema core, analytics to authenticated;
grant select, insert, update, delete on core.policy_config, core.outlier_rule, core.item_policy, core.forecast_setting to authenticated;
grant select on core.v_train_demand, core.v_test_actual to authenticated;
grant select on analytics.v_data_coverage, analytics.v_forecast_settings to authenticated;

revoke all on schema core, analytics from anon;
revoke all on core.policy_config, core.outlier_rule, core.item_policy, core.forecast_setting, core.v_train_demand, core.v_test_actual from anon;
revoke all on analytics.v_data_coverage, analytics.v_forecast_settings from anon;

notify pgrst, 'reload schema';
