-- STEP 9: 리드타임 정책화와 예측 기반 재고 Projection
-- 원천(raw) 데이터는 수정하지 않고 core/analytics 조회 계층만 확장합니다.
-- 확정수주 정책: Forecast는 기본 수요, 확정수주는 별도 확정수요 overlay로 취급합니다.
-- Forecast 결과에 확정수주를 다시 합산하지 않는 운영 계약을 전제로 하며,
-- Projection에서는 두 값을 별도 컬럼으로 유지해 한 소스가 다른 소스에 합쳐지지 않게 합니다.

create table if not exists core.leadtime_plan_history (
  history_id bigint generated by default as identity primary key,
  supplier_id text not null,
  before_planned_lead_time integer,
  after_planned_lead_time integer,
  before_basis text,
  after_basis text,
  before_service_level numeric,
  after_service_level numeric,
  before_confirmed_reason text,
  after_confirmed_reason text,
  changed_by uuid,
  changed_at timestamptz not null default now(),
  before_state jsonb,
  after_state jsonb
);

create index if not exists leadtime_plan_history_supplier_idx
  on core.leadtime_plan_history(supplier_id, changed_at desc);

alter table core.leadtime_plan_history enable row level security;
drop policy if exists leadtime_plan_history_select_admin on core.leadtime_plan_history;
create policy leadtime_plan_history_select_admin
  on core.leadtime_plan_history for select to authenticated
  using (core.is_admin());
revoke all on core.leadtime_plan_history from anon;
grant select on core.leadtime_plan_history to authenticated;

create or replace function core.audit_leadtime_plan_change()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_before jsonb;
  v_after jsonb;
  v_supplier_id text;
  v_actor uuid;
begin
  v_before := case when tg_op = 'INSERT' then null else jsonb_build_object(
    'supplier_id', old.supplier_id,
    'planned_lead_time', old.planned_lead_time,
    'basis', old.basis,
    'service_level', old.service_level,
    'confirmed_reason', old.confirmed_reason,
    'confirmed_at', old.confirmed_at
  ) end;
  v_after := case when tg_op = 'DELETE' then null else jsonb_build_object(
    'supplier_id', new.supplier_id,
    'planned_lead_time', new.planned_lead_time,
    'basis', new.basis,
    'service_level', new.service_level,
    'confirmed_reason', new.confirmed_reason,
    'confirmed_at', new.confirmed_at
  ) end;
  v_supplier_id := coalesce(new.supplier_id, old.supplier_id);
  v_actor := auth.uid();

  insert into core.leadtime_plan_history (
    supplier_id,
    before_planned_lead_time,
    after_planned_lead_time,
    before_basis,
    after_basis,
    before_service_level,
    after_service_level,
    before_confirmed_reason,
    after_confirmed_reason,
    changed_by,
    before_state,
    after_state
  )
  values (
    v_supplier_id,
    case when tg_op = 'INSERT' then null else old.planned_lead_time end,
    case when tg_op = 'DELETE' then null else new.planned_lead_time end,
    case when tg_op = 'INSERT' then null else old.basis end,
    case when tg_op = 'DELETE' then null else new.basis end,
    case when tg_op = 'INSERT' then null else old.service_level end,
    case when tg_op = 'DELETE' then null else new.service_level end,
    case when tg_op = 'INSERT' then null else old.confirmed_reason end,
    case when tg_op = 'DELETE' then null else new.confirmed_reason end,
    v_actor,
    v_before,
    v_after
  );

  insert into core.audit_log (actor, action, target_type, target_id, before, after)
  values (v_actor, 'LEADTIME_POLICY_CHANGED', 'leadtime_plan', v_supplier_id, v_before, v_after);

  return coalesce(new, old);
end;
$$;

revoke all on function core.audit_leadtime_plan_change() from public;

drop trigger if exists leadtime_plan_audit on core.leadtime_plan;
create trigger leadtime_plan_audit
  after insert or update or delete on core.leadtime_plan
  for each row execute function core.audit_leadtime_plan_change();

-- 통계 P80는 정책값이 없을 때만 사용합니다. 통계/정책 어느 쪽도 없으면 NULL입니다.
drop view if exists analytics.v_leadtime_policy_history;
drop view if exists analytics.v_leadtime_policy;
drop view if exists analytics.v_stockout_kpi;
drop view if exists analytics.v_stockout_risk;
drop view if exists analytics.v_inventory_projection;
drop view if exists core.v_inbound_qty;
drop view if exists core.v_inbound_schedule;
drop view if exists core.v_confirmed_sales_order;
drop view if exists core.v_soft_allocation;
drop view if exists core.v_inventory_snapshot;
drop view if exists core.v_leadtime_effective;

create view core.v_leadtime_effective as
with supplier_master as (
  select upper(trim("공급업체코드")) as supplier_id,
         max(nullif(trim("공급업체명"), '')) as supplier_name,
         max(nullif(trim("국가"), '')) as country
    from raw.supplier_master
   group by upper(trim("공급업체코드"))
), supplier_ids as (
  select supplier_id from core.v_leadtime_stat
  union
  select upper(trim(supplier_id)) from core.leadtime_plan
)
select ids.supplier_id,
       coalesce(st.supplier_name, sm.supplier_name, ids.supplier_id) as supplier_name,
       coalesce(st.country, sm.country) as country,
       st.n_samples,
       st.mean_days,
       st.p50_days,
       st.p80_days,
       st.p90_days,
       p.planned_lead_time,
       coalesce(p.planned_lead_time, st.p80_days) as effective_lead_time,
       case
         when p.planned_lead_time is not null then 'ADMIN_CONFIRMED'
         when st.p80_days is not null then 'ACTUAL_P80'
         else null
       end as source,
       p.basis,
       p.service_level,
       p.confirmed_reason,
       p.confirmed_at
  from supplier_ids ids
  left join core.v_leadtime_stat st on st.supplier_id = ids.supplier_id
  left join supplier_master sm on sm.supplier_id = ids.supplier_id
  left join core.leadtime_plan p on upper(trim(p.supplier_id)) = ids.supplier_id;

create view core.v_inventory_snapshot as
with parsed as (
  select upper(regexp_replace(trim("품목코드"), '[\\s\\-_]', '', 'g')) as item_id,
         nullif(regexp_replace(trim("현재고"), '[^0-9.\\-]', '', 'g'), '')::numeric as current_stock,
         nullif(trim("기준일자"), '')::date as inventory_as_of
    from raw.inventory
), latest as (
  select max(inventory_as_of) as inventory_as_of from parsed
)
select p.item_id,
       sum(p.current_stock) as current_stock,
       l.inventory_as_of
  from parsed p
  cross join latest l
 where p.inventory_as_of = l.inventory_as_of
 group by p.item_id, l.inventory_as_of;

create view core.v_inbound_schedule as
with inventory_asof as (
  select max(nullif(trim("기준일자"), '')::date) as inventory_as_of
    from raw.inventory
), scheduled as (
  select f.item_id,
         f.supplier_id,
         f.qty as scheduled_qty,
         f.order_date,
         f.due_date,
         l.effective_lead_time,
         a.inventory_as_of,
         coalesce(f.due_date, f.order_date + l.effective_lead_time) as planned_receipt_date
    from core.v_fact_shipment f
    cross join inventory_asof a
    left join core.v_leadtime_effective l on l.supplier_id = f.supplier_id
   where f.status = 'IN_TRANSIT'
     and f.qty is not null
     and f.qty > 0
)
select item_id,
       supplier_id,
       scheduled_qty,
       case
         when planned_receipt_date is null then null
         when inventory_as_of is not null and planned_receipt_date <= inventory_as_of then inventory_as_of
         else planned_receipt_date
       end as scheduled_receipt_date,
       case when planned_receipt_date is null then 'NO_LEADTIME' else 'SCHEDULED' end as reason_code,
       order_date,
       due_date,
       effective_lead_time
  from scheduled;

create view core.v_inbound_qty as
select item_id,
       sum(scheduled_qty) as inbound_qty,
       count(*) as inbound_shipments,
       min(scheduled_receipt_date) as earliest_eta
  from core.v_inbound_schedule
 where scheduled_receipt_date is not null
 group by item_id;

create view core.v_confirmed_sales_order as
select upper(regexp_replace(trim(item_id), '[\\s\\-_]', '', 'g')) as item_id,
       coalesce(requested_delivery_date, order_date) as demand_date,
       ordered_qty as confirmed_qty,
       sales_order_no,
       line_no,
       status
  from raw.sales_order
 where ordered_qty is not null
   and ordered_qty > 0
   and coalesce(requested_delivery_date, order_date) is not null
   and upper(trim(coalesce(status, ''))) in ('CONFIRMED', 'CONFIRMED_ORDER', '확정', '확정수주');

create view core.v_soft_allocation as
select upper(regexp_replace(trim(item_id), '[\\s\\-_]', '', 'g')) as item_id,
       event_date as allocation_date,
       quantity as allocated_qty,
       event_id,
       event_type,
       status
  from raw.business_event
 where quantity is not null
   and quantity > 0
   and event_date is not null
   and upper(replace(trim(coalesce(event_type, '')), ' ', '_')) in (
     'SOFT_ALLOCATION', 'SOFT_ALLOCATED', 'RESERVATION', '가예약'
   )
   and upper(trim(coalesce(status, ''))) not in ('CANCELLED', 'CANCELED', 'CLOSED', 'EXCLUDED', '취소', '종료');

grant select on core.v_leadtime_effective, core.v_inventory_snapshot,
  core.v_inbound_schedule, core.v_inbound_qty, core.v_confirmed_sales_order,
  core.v_soft_allocation to authenticated;
revoke all on core.v_leadtime_effective, core.v_inventory_snapshot,
  core.v_inbound_schedule, core.v_inbound_qty, core.v_confirmed_sales_order,
  core.v_soft_allocation from anon;

create view analytics.v_inventory_projection with (security_invoker = true) as
with recursive
setting as (
  select upper(coalesce((select granularity from core.forecast_setting where setting_key = 'DEFAULT' limit 1), 'DAILY')) as granularity
), inventory_asof as (
  select max(inventory_as_of) as inventory_as_of from core.v_inventory_snapshot
), items as (
  select item_id, item_name, supplier_id
    from core.v_item_master
   where is_active = 'Y'
), inventory as (
  select item_id, current_stock, inventory_as_of from core.v_inventory_snapshot
), leadtime as (
  select supplier_id, supplier_name, n_samples, p50_days, p80_days, p90_days,
         mean_days, planned_lead_time, effective_lead_time, source,
         basis, service_level, confirmed_at
    from core.v_leadtime_effective
), champion_selection as (
  select distinct on (c.item_id)
         c.item_id, c.forecast_run_id, c.model_id, c.model_version
    from core.champion_model c
    join core.forecast_run r on r.forecast_run_id = c.forecast_run_id
   where r.status = 'READY' and r.stale = false
   order by c.item_id, c.selected_at desc, c.champion_model_id desc
), champion_forecast as (
  select fr.item_id, fr.forecast_date,
         coalesce(fr.forecast_value, fr.p50) as forecast_demand,
         fr.model_id, fr.model_version, 'CHAMPION'::text as forecast_source
    from core.forecast_result fr
    join champion_selection c
      on c.item_id = fr.item_id
     and c.forecast_run_id = fr.forecast_run_id
     and c.model_id = fr.model_id
     and c.model_version = fr.model_version
   where coalesce(fr.forecast_value, fr.p50) is not null
), latest_ready_run as (
  select forecast_run_id
    from core.forecast_run
   where status = 'READY' and stale = false
   order by completed_at desc nulls last, created_at desc
   limit 1
), fallback_candidates as (
  select fr.item_id, fr.forecast_date,
         coalesce(fr.forecast_value, fr.p50) as forecast_demand,
         fr.model_id, fr.model_version, 'OPERATIONAL_FORECAST'::text as forecast_source,
         coalesce(mc.is_baseline, false) as is_baseline,
         fr.created_at, fr.forecast_result_id
    from core.forecast_result fr
    join latest_ready_run r on r.forecast_run_id = fr.forecast_run_id
    left join core.model_config mc
      on mc.model_id = fr.model_id and mc.model_version = fr.model_version
   where coalesce(fr.forecast_value, fr.p50) is not null
), fallback_forecast as (
  select distinct on (item_id, forecast_date)
         item_id, forecast_date, forecast_demand, model_id, model_version, forecast_source
    from fallback_candidates
   where not exists (select 1 from champion_forecast c where c.item_id = fallback_candidates.item_id)
   order by item_id, forecast_date, is_baseline desc, created_at desc, forecast_result_id desc
), forecasts as (
  select * from champion_forecast
  union all
  select * from fallback_forecast
), periods as (
  select i.item_id,
         coalesce(inv.inventory_as_of, a.inventory_as_of, current_date) as period,
         true as is_asof_period
    from items i
    left join inventory inv on inv.item_id = i.item_id
    cross join inventory_asof a
  union
  select f.item_id, f.forecast_date, false
    from forecasts f
    cross join inventory_asof a
   where a.inventory_as_of is null or f.forecast_date >= a.inventory_as_of
  union
  select s.item_id,
         case when a.inventory_as_of is not null and s.scheduled_receipt_date <= a.inventory_as_of
              then a.inventory_as_of else s.scheduled_receipt_date end,
         false
    from core.v_inbound_schedule s
    cross join inventory_asof a
   where s.scheduled_receipt_date is not null
  union
  select so.item_id,
         case when a.inventory_as_of is not null and so.demand_date <= a.inventory_as_of
              then a.inventory_as_of else so.demand_date end,
         false
    from core.v_confirmed_sales_order so
    cross join inventory_asof a
  union
  select sa.item_id,
         case when a.inventory_as_of is not null and sa.allocation_date <= a.inventory_as_of
              then a.inventory_as_of else sa.allocation_date end,
         false
    from core.v_soft_allocation sa
    cross join inventory_asof a
), period_rows as (
  select p.item_id,
         p.period,
         bool_or(p.is_asof_period) as is_asof_period,
         case when upper(coalesce(s.granularity, 'DAILY')) = 'WEEKLY' then 7
              when upper(coalesce(s.granularity, 'DAILY')) = 'MONTHLY'
                then extract(day from (date_trunc('month', p.period::timestamp) + interval '1 month' - date_trunc('month', p.period::timestamp)))::integer
              else 1 end as period_days
    from periods p
    cross join setting s
    group by p.item_id, p.period, s.granularity
), inbound_period as (
  select item_id, scheduled_receipt_date as period, sum(scheduled_qty)::numeric as scheduled_receipts
    from core.v_inbound_schedule
   where scheduled_receipt_date is not null
   group by item_id, scheduled_receipt_date
), sales_period as (
  select so.item_id,
         case when a.inventory_as_of is not null and so.demand_date <= a.inventory_as_of
              then a.inventory_as_of else so.demand_date end as period,
         sum(so.confirmed_qty)::numeric as confirmed_sales_order
    from core.v_confirmed_sales_order so
    cross join inventory_asof a
   group by so.item_id,
            case when a.inventory_as_of is not null and so.demand_date <= a.inventory_as_of
                 then a.inventory_as_of else so.demand_date end
), soft_period as (
  select sa.item_id,
         case when a.inventory_as_of is not null and sa.allocation_date <= a.inventory_as_of
              then a.inventory_as_of else sa.allocation_date end as period,
         sum(sa.allocated_qty)::numeric as soft_allocation
    from core.v_soft_allocation sa
    cross join inventory_asof a
   group by sa.item_id,
            case when a.inventory_as_of is not null and sa.allocation_date <= a.inventory_as_of
                 then a.inventory_as_of else sa.allocation_date end
), flow_rows as (
  select pr.item_id,
         pr.period,
         pr.is_asof_period,
         pr.period_days,
         coalesce(max(ins.scheduled_receipts), 0)::numeric as scheduled_receipts,
         coalesce(max(so.confirmed_sales_order), 0)::numeric as confirmed_sales_order,
         coalesce(max(sa.soft_allocation), 0)::numeric as soft_allocation,
         max(f.forecast_demand) as forecast_demand,
         max(f.forecast_source) as forecast_source,
         max(f.model_id) as forecast_model_id,
         max(f.model_version) as forecast_model_version,
         max(i.item_name) as item_name,
         max(i.supplier_id) as supplier_id,
         max(inv.current_stock) as current_stock,
         max(inv.inventory_as_of) as inventory_as_of,
         max(l.supplier_name) as supplier_name,
         max(l.n_samples) as n_samples,
         max(l.p50_days) as p50_days,
         max(l.p80_days) as p80_days,
         max(l.p90_days) as p90_days,
         max(l.mean_days) as mean_days,
         max(l.planned_lead_time) as planned_lead_time,
         max(l.effective_lead_time) as effective_lead_time,
         max(l.source) as lead_time_source,
         max(l.basis) as lead_time_basis,
         max(l.service_level) as service_level,
         max(l.confirmed_at) as lead_time_confirmed_at
    from period_rows pr
    join items i on i.item_id = pr.item_id
    left join inventory inv on inv.item_id = pr.item_id
    left join leadtime l on l.supplier_id = i.supplier_id
    left join inbound_period ins
      on ins.item_id = pr.item_id
     and ins.period = pr.period
    left join sales_period so
      on so.item_id = pr.item_id
     and so.period = pr.period
    left join soft_period sa
      on sa.item_id = pr.item_id
     and sa.period = pr.period
    left join forecasts f
      on f.item_id = pr.item_id and f.forecast_date = pr.period
   group by pr.item_id, pr.period, pr.is_asof_period, pr.period_days
), source_counts as (
  select i.item_id,
         (select count(*) from raw.sales_order r where upper(regexp_replace(trim(r.item_id), '[\\s\\-_]', '', 'g')) = i.item_id) as sales_source_rows,
         (select count(*) from raw.business_event r where upper(regexp_replace(trim(r.item_id), '[\\s\\-_]', '', 'g')) = i.item_id) as soft_source_rows
    from items i
), ordered as (
  select f.*, sc.sales_source_rows, sc.soft_source_rows,
         row_number() over (partition by f.item_id order by f.period) as rn
    from flow_rows f
    join source_counts sc on sc.item_id = f.item_id
), projected (item_id, period, is_asof_period, period_days, scheduled_receipts,
             confirmed_sales_order, soft_allocation, forecast_demand, forecast_source,
             forecast_model_id, forecast_model_version, item_name, supplier_id,
             current_stock, inventory_as_of, supplier_name, n_samples, p50_days,
             p80_days, p90_days, mean_days, planned_lead_time, effective_lead_time,
             lead_time_source, lead_time_basis, service_level, lead_time_confirmed_at,
             sales_source_rows, soft_source_rows, rn, beginning_inventory,
             ending_projected_inventory) as (
  select o.item_id, o.period, o.is_asof_period, o.period_days, o.scheduled_receipts,
         o.confirmed_sales_order, o.soft_allocation, o.forecast_demand, o.forecast_source,
         o.forecast_model_id, o.forecast_model_version, o.item_name, o.supplier_id,
         o.current_stock, o.inventory_as_of, o.supplier_name, o.n_samples, o.p50_days,
         o.p80_days, o.p90_days, o.mean_days, o.planned_lead_time, o.effective_lead_time,
         o.lead_time_source, o.lead_time_basis, o.service_level, o.lead_time_confirmed_at,
         o.sales_source_rows, o.soft_source_rows, o.rn,
         o.current_stock as beginning_inventory,
         case
           when o.current_stock is null then null
           when o.forecast_demand is null and not o.is_asof_period then null
           else o.current_stock + o.scheduled_receipts - o.confirmed_sales_order - o.soft_allocation
                - coalesce(o.forecast_demand, 0)
         end as ending_projected_inventory
    from ordered o
   where o.rn = 1
  union all
  select n.item_id, n.period, n.is_asof_period, n.period_days, n.scheduled_receipts,
         n.confirmed_sales_order, n.soft_allocation, n.forecast_demand, n.forecast_source,
         n.forecast_model_id, n.forecast_model_version, n.item_name, n.supplier_id,
         n.current_stock, n.inventory_as_of, n.supplier_name, n.n_samples, n.p50_days,
         n.p80_days, n.p90_days, n.mean_days, n.planned_lead_time, n.effective_lead_time,
         n.lead_time_source, n.lead_time_basis, n.service_level, n.lead_time_confirmed_at,
         n.sales_source_rows, n.soft_source_rows, n.rn,
         p.ending_projected_inventory as beginning_inventory,
         case when p.ending_projected_inventory is null or n.forecast_demand is null then null
              else p.ending_projected_inventory + n.scheduled_receipts - n.confirmed_sales_order
                   - n.soft_allocation - n.forecast_demand end as ending_projected_inventory
    from projected p
    join ordered n on n.item_id = p.item_id and n.rn = p.rn + 1
), item_metrics as (
  select item_id,
         min(item_name) as item_name,
         min(supplier_id) as supplier_id,
         min(supplier_name) as supplier_name,
         min(inventory_as_of) as projection_as_of,
         max(current_stock) filter (where is_asof_period) as current_stock,
         max(effective_lead_time) as effective_lead_time,
         max(planned_lead_time) as planned_lead_time,
         max(lead_time_source) as lead_time_source,
         max(n_samples) as n_samples,
         max(p50_days) as p50_days,
         max(p80_days) as p80_days,
         max(p90_days) as p90_days,
         max(mean_days) as mean_days,
         max(lead_time_basis) as lead_time_basis,
         max(service_level) as service_level,
         max(lead_time_confirmed_at) as lead_time_confirmed_at,
         count(*) filter (where forecast_demand is not null) as forecast_period_count,
         sum(forecast_demand) filter (where forecast_demand is not null) as forecast_total,
         sum(period_days) filter (where forecast_demand is not null) as forecast_days,
         min(period) filter (where ending_projected_inventory <= 0 and forecast_demand is not null) as stockout_period,
         (array_agg(ending_projected_inventory order by period desc))[1] as last_ending_inventory,
         sum(period_days) as horizon_days,
         max(sales_source_rows) as sales_source_rows,
         max(soft_source_rows) as soft_source_rows
    from projected
   group by item_id
), policy as (
  select max(safety_buffer_days) filter (where active) as safety_buffer_days
    from core.policy_config
   where policy_key in ('DEFAULT', 'INVENTORY_PROJECTION')
), classified as (
  select m.*,
         case when m.forecast_days > 0 then m.forecast_total / m.forecast_days else null end as forecast_daily_avg,
         p.safety_buffer_days,
         case
           when m.current_stock is null then 'CALCULATION_UNAVAILABLE'
           when m.effective_lead_time is null then 'CALCULATION_UNAVAILABLE'
           when m.forecast_period_count = 0 then 'CALCULATION_UNAVAILABLE'
           when m.forecast_total is null or m.forecast_total <= 0 then 'CALCULATION_UNAVAILABLE'
           when m.lead_time_source = 'ACTUAL_P80' and coalesce(m.n_samples, 0) < 2 then 'CALCULATION_UNAVAILABLE'
           when m.stockout_period is null then 'SAFE'
           when m.stockout_period < m.projection_as_of + m.effective_lead_time then 'CRITICAL'
           when m.stockout_period <= m.projection_as_of + m.effective_lead_time
                or (p.safety_buffer_days is not null and m.stockout_period <= m.projection_as_of + m.effective_lead_time + p.safety_buffer_days::integer)
             then 'WARNING'
           else 'SAFE'
         end as risk_status,
         case
           when m.current_stock is null then 'NO_INVENTORY_DATA'
           when m.effective_lead_time is null then 'NO_LEADTIME'
           when m.forecast_period_count = 0 then 'NO_FORECAST'
           when m.forecast_total is null or m.forecast_total <= 0 then 'NO_USAGE_HISTORY'
           when m.lead_time_source = 'ACTUAL_P80' and coalesce(m.n_samples, 0) < 2 then 'INSUFFICIENT_SAMPLE'
           else null
         end as calculation_reason
    from item_metrics m
    cross join policy p
)
select p.item_id,
       p.item_name,
       p.supplier_id,
       p.supplier_name,
       c.projection_as_of,
       p.period,
       p.period_days,
       p.beginning_inventory,
       p.scheduled_receipts,
       p.confirmed_sales_order,
       p.soft_allocation,
       p.forecast_demand,
       p.ending_projected_inventory,
       c.stockout_period,
       c.stockout_period as stockout_date,
       case
         when c.forecast_daily_avg is null or c.forecast_daily_avg <= 0 then null
         when c.stockout_period is not null then greatest(0, c.stockout_period - c.projection_as_of)::numeric
         when c.last_ending_inventory is null then null
         else c.horizon_days + greatest(c.last_ending_inventory, 0) / c.forecast_daily_avg
       end as days_of_supply,
       case
         when c.forecast_daily_avg is null or c.forecast_daily_avg <= 0 then null
         when c.stockout_period is not null then greatest(0, c.stockout_period - c.projection_as_of)::numeric / (365.25 / 12)
         when c.last_ending_inventory is null then null
         else (c.horizon_days + greatest(c.last_ending_inventory, 0) / c.forecast_daily_avg) / (365.25 / 12)
       end as months_of_supply,
       c.risk_status,
       c.calculation_reason as reason_code,
       p.effective_lead_time,
       p.lead_time_source,
       p.forecast_source,
       p.forecast_model_id,
       p.forecast_model_version,
       case when p.sales_source_rows = 0 then 'NO_SOURCE_DATA'
            when p.confirmed_sales_order > 0 then 'DATA_AVAILABLE'
            else 'STRUCTURAL_ZERO' end as confirmed_sales_order_status,
       case when p.soft_source_rows = 0 then 'NO_SOURCE_DATA'
            when p.soft_allocation > 0 then 'DATA_AVAILABLE'
            else 'STRUCTURAL_ZERO' end as soft_allocation_status,
       case when p.soft_source_rows = 0 then 'NO_SOFT_ALLOCATION_DATA' else null end as soft_allocation_reason,
       c.forecast_daily_avg,
       c.safety_buffer_days,
       'BASE_FORECAST_PLUS_EXPLICIT_CONFIRMED_ORDER'::text as confirmed_sales_order_policy,
       c.forecast_period_count,
       c.n_samples,
       c.p50_days,
       c.p80_days,
       c.p90_days,
       c.mean_days
  from projected p
  join classified c on c.item_id = p.item_id;

create view analytics.v_stockout_risk with (security_invoker = true) as
with summary as (
  select item_id,
         min(item_name) as item_name,
         min(supplier_id) as supplier_id,
         min(supplier_name) as supplier_name,
         min(projection_as_of) as projection_as_of,
         (array_agg(beginning_inventory order by period))[1] as current_stock,
         sum(scheduled_receipts) as inbound_qty,
         max(effective_lead_time) as planned_lead_time,
         max(forecast_daily_avg) as daily_usage_avg,
         min(stockout_period) as stockout_date,
         max(risk_status) as risk_status,
         max(reason_code) as reason,
         max(days_of_supply) as days_of_supply,
         max(months_of_supply) as months_of_supply,
         max(lead_time_source) as lead_time_source,
         max(forecast_source) as forecast_source,
         max(forecast_model_id) as forecast_model_id,
         max(forecast_model_version) as forecast_model_version,
         max(n_samples) as n_samples,
         max(p50_days) as p50_days,
         max(p80_days) as p80_days,
         max(p90_days) as p90_days,
         max(mean_days) as mean_days,
         sum(scheduled_receipts) filter (where period >= projection_as_of) as scheduled_receipts,
         sum(confirmed_sales_order) as confirmed_sales_order,
         sum(soft_allocation) as soft_allocation,
         sum(forecast_demand) as forecast_demand
    from analytics.v_inventory_projection
   group by item_id
), usage as (
  select item_id, max(cv) as cv from core.v_usage_effective group by item_id
)
select s.item_id,
       s.item_name,
       s.supplier_id,
       s.supplier_name,
       s.current_stock,
       s.inbound_qty,
       s.current_stock as available_qty,
       s.daily_usage_avg,
       u.cv,
       s.planned_lead_time,
       case when s.stockout_date is null or s.projection_as_of is null then null
            else greatest(0, s.stockout_date - s.projection_as_of)::numeric end as stockout_days,
       s.stockout_date,
       s.risk_status,
       s.reason,
       s.projection_as_of,
       s.days_of_supply,
       s.months_of_supply,
       s.lead_time_source,
       s.forecast_source,
       s.forecast_model_id,
       s.forecast_model_version,
       s.n_samples,
       s.p50_days,
       s.p80_days,
       s.p90_days,
       s.mean_days,
       s.scheduled_receipts,
       s.confirmed_sales_order,
       s.soft_allocation,
       s.forecast_demand
  from summary s
  left join usage u on u.item_id = s.item_id;

create view analytics.v_stockout_kpi with (security_invoker = true) as
select count(*) as n_items,
       count(*) filter (where risk_status = 'CRITICAL') as n_critical,
       count(*) filter (where risk_status = 'WARNING') as n_warning,
       count(*) filter (where risk_status = 'SAFE') as n_safe,
       count(*) filter (where risk_status = 'CALCULATION_UNAVAILABLE') as n_unavailable,
       count(*) filter (where risk_status = 'CALCULATION_UNAVAILABLE') as n_unknown,
       count(*) filter (where stockout_days <= 30) as n_within_30d,
       avg(stockout_days) filter (where stockout_days is not null) as avg_stockout_days
  from analytics.v_stockout_risk;

create view analytics.v_leadtime_policy with (security_invoker = true) as
select i.item_id,
       i.item_name,
       i.supplier_id,
       coalesce(l.supplier_name, i.supplier_id) as supplier_name,
       l.country,
       l.mean_days,
       l.p50_days,
       l.p80_days,
       l.p90_days,
       l.planned_lead_time as admin_lead_time,
       l.effective_lead_time,
       l.source,
       l.basis,
       l.service_level,
       l.confirmed_reason,
       l.confirmed_at
  from core.v_item_master i
  left join core.v_leadtime_effective l on l.supplier_id = i.supplier_id
 where i.is_active = 'Y';

create view analytics.v_leadtime_policy_history with (security_invoker = true) as
select h.history_id,
       h.supplier_id,
       coalesce(max(nullif(trim(s."공급업체명"), '')), h.supplier_id) as supplier_name,
       h.before_planned_lead_time,
       h.after_planned_lead_time,
       h.before_basis,
       h.after_basis,
       h.before_service_level,
       h.after_service_level,
       h.before_confirmed_reason,
       h.after_confirmed_reason,
       h.changed_by,
       h.changed_at,
       h.before_state,
       h.after_state
  from core.leadtime_plan_history h
  left join raw.supplier_master s on upper(trim(s."공급업체코드")) = upper(trim(h.supplier_id))
 group by h.history_id, h.supplier_id, h.before_planned_lead_time,
          h.after_planned_lead_time, h.before_basis, h.after_basis,
          h.before_service_level, h.after_service_level,
          h.before_confirmed_reason, h.after_confirmed_reason,
          h.changed_by, h.changed_at, h.before_state, h.after_state;

grant select on analytics.v_inventory_projection, analytics.v_stockout_risk,
  analytics.v_stockout_kpi, analytics.v_leadtime_policy,
  analytics.v_leadtime_policy_history to authenticated;
revoke all on analytics.v_inventory_projection, analytics.v_stockout_risk,
  analytics.v_stockout_kpi, analytics.v_leadtime_policy,
  analytics.v_leadtime_policy_history from anon;
